# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llmsurgery',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/llmsurgery',
                'lib_path': 'llmsurgery'},
  'syms': {'llmsurgery.core': {'llmsurgery.core.foo': ('core.html#foo', 'llmsurgery/core.py')}}}
