"""Find, search, edit, and compact Claude Code sessions and prompt history

Find, read, search, and edit Claude Code session transcripts and prompt history on this machine.

## Session layout

The transcript format, its `~/.claude/projects` paths, and the read/write primitives (`sess_dir`, `sess_file`, `cur_sess`, `load_recs`, `load_sess`, `sess_thread`, `rec_txt`, `mk_rec`, `save_sess`, `msgs2sess`, ...) live in `fastclaude.session`, which this module builds on. Here `rec_role` classifies records (a user record carrying tool results counts as `tool`), `conv_recs` drops Claude Code's bookkeeping, and `resolve_session` accepts an id or a `/rename` title.

Claude also appends every typed prompt to `~/.claude/history.jsonl`, with its project directory and a millisecond timestamp. `prompt_hist` reads it into filterable rows. This can recover the user's side when a transcript has been lost or rewritten.

## Reading workflow

To find something that was said - an earlier discussion, a decision, work lost to compaction - start with `sess2dlg`, not with the records. It costs a fraction of a second even on a 50MB transcript, and turns tens of thousands of records into a dialog of a few dozen messages: `d.summary()` is the map (one sized row per message, a prompt's reply on its own line), `d.find_msgs(pat)` the search, `view_msg`/`view_msgs` the read. `doc(aidialog.dlgskill)` covers that layer, and a dialog written with `write_ipynb` is an ordinary ipynb whose prompt sources carry their replies, so `rgapi`'s `nbrg` searches saved sessions across files, replies included.

Work at the record level for surgery, or when a record's envelope is itself the question: locate with `sess_file`, `cur_sess`, or `resolve_session`; load with `load_sess`, or `load_recs` for an arbitrary path; select the active thread with `sess_thread` and `conv_recs`; search readable text with `sess_search`, whose hits each carry their record on `.rec`; read a slice with `show_recs`. Prefer `sess_search` to grepping JSONL, since raw files contain base64 data, signatures, and envelope noise.

Reading functions do not modify transcripts. `save_sess`, `append_sess`, `fork_curated`, and the compaction functions do. Read their docs and inspect the target records before calling them; `save_sess` replaces a whole session file.

Docs: https://AnswerDotAI.github.io/llmsurgery/ant.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_ant.ipynb.

# %% auto #0
__all__ = ['conv_recs', 'rec_role', 'SessHits', 'sess_search', 'show_recs', 'PromptHist', 'prompt_hist', 'is_think_rec',
           'strip_think', 'trunc_tools', 'reid_recs', 'name_sess', 'sess_by_name', 'fork_curated', 'dlg2msgs',
           'dlg2sess', 'ToolReference', 'recs2chat', 'sess2dlg', 'resolve_session', 'split_compaction', 'sess_meta',
           'compact_records', 'prepare_compaction', 'append_compaction', 'compact_session', 'run_locked_agent']

# %% ../nbs/03_ant.ipynb #09dc6bf6
import asyncio, base64, re
from dataclasses import dataclass
from datetime import datetime
from fastcore.utils import *
from fastllm.anthropic import denorm_msgs, norm_tr_parts
from fastllm.chat import mk_msg
from aidialog.msg_parts import Msg, Part, Text, Thinking, ToolUse, ToolResult, tool_text
from aidialog.hist import dlg2chat, chat2dlg
from aidialog.dialog import *
from .compact import *
from .utils import MAXLEN
from fastclaude.session import *
from fastclaude.core import astream

# %% ../nbs/03_ant.ipynb #f9d47bbc
def conv_recs(
    recs, # Session records, e.g. from `load_sess`
):
    "Just the records carrying conversation messages, dropping Claude Code's bookkeeping"
    return L(r for r in recs if r.get('type') in ('user','assistant') and 'message' in r)

def rec_role(
    r, # A session record
):
    "The conversational role of `r`: a user record carrying tool results counts as `tool`"
    r = obj2dict(r)
    c = r['message']['content']
    if r['type']=='user' and isinstance(c, list) and any(b.get('type')=='tool_result' for b in c): return 'tool'
    return r['type']

# %% ../nbs/03_ant.ipynb #defb1a03
def _trunc_sz(s, mx):
    "Truncate `s` to `mx` characters, ending in a humanized `[size]` when it was cut"
    return truncstr(s, mx, suf=f'…[{humanize(len(s))}]')

def _preview(t, m, maxlen):
    h = maxlen//2
    s,e = max(0,m.start()-h),min(len(t),m.end()+h)
    res = ('…' if s else '')+t[s:e].replace('\n',' ')+('…' if e<len(t) else '')
    return res+f'[{humanize(len(t))}]' if s or e<len(t) else res


# %% ../nbs/03_ant.ipynb #70515bc9
class SessHits(L):
    "Search hits with a match-centered preview per line, each carrying its record on `.rec`"
    recs = None # Every record searched, set by `sess_search`; carried through selections
    def _new(self, items, *args, **kw):
        res = super()._new(items, *args, **kw)
        res.recs = self.recs
        return res
    def __repr__(self): return '\n'.join(f"{h.i:5} {h.role:9} {h.ts[:16]} {h.preview}" for h in self)

def sess_search(
    pat, # Regex to find in conversation text
    sid=None, # Session id; the current session if None
    cwd=None, # Project directory; the current directory if None
    maxlen=MAXLEN, # Preview characters shown around a hit's first match
    recs=None, # Already-loaded records; if given, `sid` and `cwd` are ignored
):
    "Search conversation records: `SessHits` rows, each carrying its own record on `.rec`, with every searched record on `.recs`"
    recs = conv_recs(load_sess(sid,cwd) if recs is None else recs)
    res = SessHits()
    for i,r in enumerate(recs):
        if m := re.search(pat,t:=rec_txt(r)): res.append(AttrDict(i=i,role=rec_role(r),ts=r['timestamp'],preview=_preview(t,m,maxlen),rec=r))
    res.recs = recs
    return res

# %% ../nbs/03_ant.ipynb #58f5cf47
def show_recs(
    recs, # Session records, e.g. a slice of `SessHits.recs`
    mx=500, # Characters of text shown per record
    showall:bool=False, # Include bookkeeping records?
):
    "A readable transcript of records in `recs`; conversation records only unless `showall`"
    def _s(r):
        t = rec_txt(r)
        t = _trunc_sz(t, mx)
        role = rec_role(r) if r.get('type') in ('user','assistant') else ':'.join(filter(None,(r.get('type'),r.get('subtype'))))
        return f"--- {role} {r.get('timestamp','')[:19]} ---\n{t}"
    return PrettyString('\n'.join(_s(r) for r in (recs if showall else conv_recs(recs))))

# %% ../nbs/03_ant.ipynb #343ac533
class PromptHist(list):
    "Prompt-history rows in local time, one line per prompt"
    def __repr__(self): return '\n'.join(f"{h.ts:%Y-%m-%d %H:%M} {Path(h.project).name:>12} {_trunc_sz(h.display.replace(chr(10),' '), 120)}" for h in self)

def prompt_hist(
    project=None, # Only prompts for the project at this directory; all projects if None
    since=None, # Only prompts at or after this datetime or ISO string; a TZ-less string is on the same local clock as the returned times, Z/offset strings are converted
    pat=None, # Only prompts whose text matches this regex
    path=None, # History file; Claude Code's own (`~/.claude/history.jsonl`) if None
):
    "Claude Code's global prompt history, oldest first: every prompt typed on this machine, kept even when its transcript is gone"
    rows = Path(path or Path.home()/'.claude'/'history.jsonl').read_jsonl()
    res = [AttrDict(ts=datetime.fromtimestamp(r['timestamp']/1000), project=r.get('project',''), display=r.get('display',''))  # chkstyle: ignore-node
           for r in rows if isinstance(r.get('timestamp'), (int,float))]
    if project: res = [r for r in res if r.project==str(Path(project).expanduser().resolve())]
    if isinstance(since, str): since = datetime.fromisoformat(since)
    if since and since.tzinfo: since = since.astimezone().replace(tzinfo=None)
    if since: res = [r for r in res if r.ts>=since]
    if pat: res = [r for r in res if re.search(pat, r.display)]
    return PromptHist(res)

# %% ../nbs/03_ant.ipynb #9e265e88
def is_think_rec(
    r, # Session record
):
    "Whether `r` is an assistant record containing only thinking blocks"
    c = nested_idx(r, 'message', 'content')
    return r.get('type')=='assistant' and is_listy(c) and bool(c) and all(b.get('type')=='thinking' for b in c)

def strip_think(
    recs, # Session records
):
    "Drop records whose message content is only `thinking` blocks; resume does not need them"
    return L(recs).filter(lambda r:not is_think_rec(r))

# %% ../nbs/03_ant.ipynb #a56fc348
def _trunc_deep(o, mx):
    if isinstance(o, str): return o if len(o)<=mx else o[:mx]+f'…[+{len(o)-mx} chars]'
    if isinstance(o, dict): return {k:_trunc_deep(v, mx) for k,v in o.items()}
    if is_listy(o): return [_trunc_deep(x, mx) for x in o]
    return o

def trunc_tools(
    recs, # Session records
    mx=2000, # Maximum characters per string in tool inputs and results
):
    "Copies of `recs` with strings in tool_use inputs and tool_result content truncated to `mx` characters"
    recs = [obj2dict(r) for r in recs]
    for r in recs:
        c = r.get('message', {}).get('content', '')
        if isinstance(c, str): continue
        for b in c:
            if b.get('type')=='tool_use': b['input'] = _trunc_deep(b.get('input', {}), mx)
            elif b.get('type')=='tool_result' and 'content' in b: b['content'] = _trunc_deep(b['content'], mx)
    return L(recs)

# %% ../nbs/03_ant.ipynb #7ffe1bb4
def reid_recs(
    recs, # Records in conversation order
    key='', # Salt: the same records and key give the same ids
    ts=None, # If given, set every record's timestamp to this
):
    "Deterministically re-derive record uuids, tool_use ids, and API metadata, so one capture gives one file"
    recs,ids = [obj2dict(r) for r in recs],{}
    for i,r in enumerate(recs):
        c = r.get('message', {}).get('content', '')
        if not isinstance(c, str):
            for j,b in enumerate(c):
                if b.get('type')=='tool_use':
                    nid = 'toolu_'+stable_uuid(f'{key}:{i}:{j}').replace('-', '')[:24]
                    ids[b['id']],b['id'] = nid,nid
                elif b.get('type')=='tool_result' and b.get('tool_use_id') in ids: b['tool_use_id'] = ids[b['tool_use_id']]
        uid = stable_uuid(f'{key}:{i}')
        if 'uuid' in r: ids[r['uuid']] = uid
        r['uuid'] = uid
        if ts: r['timestamp'] = ts
        if r.get('type')=='assistant':
            r['requestId'] = 'req_'+stable_uuid(f'{uid}:req').replace('-', '')[:24]
            r['message']['id'] = 'msg_'+stable_uuid(f'{uid}:msg').replace('-', '')[:24]
    for r in recs:
        for k,v in r.items():
            if isinstance(v, str) and v in ids: r[k] = ids[v]
    return L(recs)

# %% ../nbs/03_ant.ipynb #58e65644
def name_sess(sid, name, cwd=None):
    "Name session `sid` and return it"
    recs = [dict(type='custom-title', customTitle=name, sessionId=sid), dict(type='agent-name', agentName=name, sessionId=sid)]
    with sess_file(sid, cwd).open('a') as f: f.writelines(xdumps(r)+'\n' for r in recs)
    return sid

# %% ../nbs/03_ant.ipynb #a6d54271
def sess_by_name(name, cwd='.'):
    "Find the first project session transcript with latest custom title `name`"
    for f in sess_dir(Path(cwd).expanduser()).glob('*.jsonl'):
        recs = reversed(f.read_jsonl())
        if first((r.get('customTitle') for r in recs if r.get('type')=='custom-title'))==name: return f

# %% ../nbs/03_ant.ipynb #6db09ecc
def fork_curated(
    sid=None, # Session id to fork; `cur_sess()` if None
    cwd=None, # Project directory; passed to `sess_file` via `load_sess`
    mx=None, # If given, truncate tool input/output strings to `mx` characters
    think=True, # Keep thinking records?
    key=None, # If given, record and session ids re-derive deterministically from this salt
    name=None, # Optional name for the new session
):
    "Write a munged copy of session `sid` under a fresh id, returning the new id to resume"
    recs = sess_thread(load_sess(sid, cwd))
    if not think: recs = strip_think(recs)
    if mx is not None: recs = trunc_tools(recs, mx)
    if key: recs = reid_recs(recs, key)
    sid = save_sess(list(recs), stable_uuid(key) if key else None, cwd)
    return name_sess(sid, name, cwd) if name else sid

# %% ../nbs/03_ant.ipynb #7b8d57fa
def dlg2msgs(
    dlg, # A `Dialog`, ending with a prompt
    aim_info=None, # Model capability dict for media handling; images enabled if None
):
    "Anthropic-style messages for `dlg`: each reply's tool calls recovered as real blocks, prompts as bare content (no serving envelope)"
    return denorm_msgs(dlg2chat(dlg, aim_info, plain=True))

def dlg2sess(
    dlg, # The dialog to convert
    cwd=None, # Project directory for the session; the current directory if None
    key='dlg2sess', # Salt for deterministic record ids
    aim_info=None, # Model capability dict; images enabled if None
):
    "Write `dlg` as a Claude Code session for the project at `cwd`, returning the session id to resume; tagged raw messages re-emit their original records"
    recs = msgs2recs(dlg2msgs(dlg, aim_info), key=key, cwd=str(Path(cwd or '.').expanduser().resolve()))
    raws,t = {},-1
    for m in dlg.messages:
        if m.msg_type==sprompt: t += 1
        elif m.msg_type==sraw and m.meta.get('rec_kind'): raws.setdefault(t, []).append(dict(m.meta['rec']))
    if raws:
        out,t = [],-1
        for r in recs:
            if r['type']=='user' and rec_role(r)!='tool':
                out += raws.get(t, [])
                t += 1
            out.append(r)
        out += raws.get(t, [])
        recs = out
    return save_sess(recs, stable_uuid(f'{key}:{dlg.name}'), cwd)

# %% ../nbs/03_ant.ipynb #1cf53a7a
@dataclass
class ToolReference(Part, tag='tool_reference'):
    "A deferred-tool reference in a Claude Code tool result"
    tool_name: str = ''

@patch(as_prop=True)
def formatted(self:ToolReference): return f'<tool_reference tool="{self.tool_name}"/>'

# %% ../nbs/03_ant.ipynb #16af5ac6
def _tr_txt(b):
    c = b.get('content', '')
    return c if isinstance(c, str) else tool_text(norm_tr_parts(c))

def _norm_user(content):
    if isinstance(content, str): return mk_msg(content)
    items = []
    for b in content:
        if b['type']=='text': items.append(b['text'])
        elif b['type']=='image': items.append(base64.b64decode(b['source']['data']))
        else: raise ValueError(f"unsupported user block: {b['type']}")
    return mk_msg(items)

def recs2chat(
    recs, # Session records, e.g. from `load_sess`
):
    "Canonical fastllm messages for the conversation records in `recs`"
    msgs,names = [],{}
    def add(m):
        m.meta = meta
        msgs.append(m)
    for r in recs:
        r = obj2dict(r)
        if r.get('type') not in ('user','assistant'): continue
        c = r['message']['content']
        meta = {k:v for k,v in dict(created=r.get('timestamp'), uid=r.get('uuid')).items() if v} or None
        if isinstance(c, str) and r['type']=='assistant': c = [dict(type='text', text=c)]
        if r['type']=='assistant':
            parts = []
            for b in c:
                if b['type']=='text': parts.append(Text(b['text']))
                elif b['type']=='thinking': parts.append(Thinking(b.get('thinking','')))
                elif b['type']=='tool_use':
                    names[b['id']] = b['name']
                    parts.append(ToolUse(id=b['id'], name=b['name'], arguments=b.get('input', {})))
                elif b['type']=='fallback': continue  # mid-response model-switch bookkeeping, no content
                else: raise ValueError(f"unsupported assistant block: {b['type']}")
            add(Msg(role='assistant', content=parts))
        elif rec_role(r)=='tool':
            if not all(b.get('type')=='tool_result' for b in c): raise ValueError('record mixes tool_result with other blocks')
            add(Msg(role='tool', content=[ToolResult(id=b['tool_use_id'], name=names.get(b['tool_use_id']),
                text=_tr_txt(b)) for b in c]))
        else: add(_norm_user(c))
    return msgs

# %% ../nbs/03_ant.ipynb #abc4a08a
def sess2dlg(
    sid=None, # Session id; `cur_sess()` if None
    cwd=None, # Project directory; passed to `sess_file` via `load_sess`
    name=None, # Dialog name; the session id if None
    mx=2000, # Maximum characters per rendered tool input/output string; None disables truncation (see `hist2fmt`)
    recs=None, # Already-loaded records; if given, `sid` and `cwd` are ignored
):
    "The conversation of a session as a dialog, one prompt per user turn; `system` records ride along as tagged raws"
    if recs is None:
        sid = sid or cur_sess(cwd)
        recs = load_sess(sid,cwd)
    recs = strip_think(sess_thread(L(recs)))
    dlg = chat2dlg(recs2chat(recs), name or sid or 'session', mx=mx)
    prompts,t,anchor = [m for m in dlg.messages if m.msg_type==sprompt],-1,None
    for r in recs:
        r = obj2dict(r)
        if r['type']=='user' and rec_role(r)!='tool':
            t += 1
            anchor = prompts[t]
            anchor.meta['timestamp'] = r.get('timestamp')
        elif r['type']=='assistant':
            if u := nested_idx(r,'message','usage'): prompts[t].meta['usage'] = u
        elif r['type']=='system':
            kw = dict(after=anchor) if anchor else dict(idx=0)
            kind = ':'.join(filter(None,(r['type'],r.get('subtype'))))
            anchor = dlg.mk_message('', msg_type=sraw, meta=dict(rec_kind=kind,rec=r), **kw)
    return dlg

# %% ../nbs/03_ant.ipynb #3991610a
def resolve_session(ref=None, cwd='.'):
    "Resolve a session id or custom title to `(sid,path)`"
    cwd = Path(cwd).expanduser()
    ref = ref or cur_sess(cwd)
    if ref is None: raise FileNotFoundError(f'No transcripts found for the project at {cwd}')
    path = sess_file(ref, cwd)
    if path.exists(): return ref,path
    path = sess_by_name(ref, cwd)
    if path: return path.stem,path
    raise FileNotFoundError(f'No session named or identified by {ref!r} in {cwd}')

# %% ../nbs/03_ant.ipynb #558f940f
def _is_synthetic_compact(r):
    "Check whether `r` is an llmsurgery compact summary"
    return bool(r.get('isCompactSummary') and r.get('llmsurgeryCompact'))

def _is_compact_wrapper(r):
    "Check whether `r` belongs to the synthetic `/compact` display"
    return bool(r.get('llmsurgeryCompact'))

# %% ../nbs/03_ant.ipynb #d00d96be
def split_compaction(recs):
    "Return the prior compaction's text and records added after it"
    thread = sess_thread(recs)
    idxs = [i for i,r in enumerate(thread) if r.get('isCompactSummary')]
    if not idxs: return '',thread
    i,j = idxs[-1],idxs[-1]+1
    while j<len(thread) and _is_compact_wrapper(thread[j]): j += 1
    prior = compact_body(rec_txt(thread[i])) if _is_synthetic_compact(thread[i]) else rec_txt(thread[i])
    return prior,thread[j:]

# %% ../nbs/03_ant.ipynb #349542e6
def sess_meta(recs):
    "Latest available session metadata for synthetic records"
    ks = 'session_id userType entrypoint cwd sessionId version gitBranch slug'.split()
    vals = {k:next((r[k] for r in reversed(recs) if r.get(k) is not None), None) for k in ks}
    return {k:v for k,v in vals.items() if v is not None}

# %% ../nbs/03_ant.ipynb #87077273
def compact_records(recs, content, pre_toks, post_toks):
    "Create a tagged compact boundary, summary, and visible `/compact` records"
    meta,tag = sess_meta(recs),dict(llmsurgeryCompact=True, llmsurgeryCompactVersion=1)
    prior = max((o.get('compactMetadata', {}).get('cumulativeDroppedTokens', 0) for o in recs), default=0)
    boundary = mk_rec('system', '', cwd=meta['cwd'])
    boundary.pop('message')
    boundary.update(meta)
    boundary.update(tag)
    boundary.update(subtype='compact_boundary', content='', level='info', isMeta=False,
        compactMetadata=dict(preTokens=pre_toks, postTokens=post_toks, cumulativeDroppedTokens=prior+max(0, pre_toks-post_toks)))
    summary = mk_rec('user', content, cwd=meta['cwd'], ts=boundary['timestamp'],
        promptId=stable_uuid(f"{boundary['uuid']}:prompt"), isVisibleInTranscriptOnly=True, isCompactSummary=True)
    summary.update(meta)
    summary.update(tag)
    summary['parentUuid'] = boundary['uuid']
    caveat = mk_rec('user', '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>', cwd=meta['cwd'])
    command = mk_rec('user', '<command-name>/compact</command-name>\n            <command-message>compact</command-message>\n            <command-args></command-args>', cwd=meta['cwd'])
    stdout = mk_rec('user', '<local-command-stdout>Compacted (ctrl+o to see full summary)</local-command-stdout>', cwd=meta['cwd'])
    for prev,o in zip((summary,caveat,command), (caveat,command,stdout)): o['parentUuid'] = prev['uuid']
    for o in (caveat,command,stdout): o.update(meta); o.update(tag)  # chkstyle: ignore
    return L(boundary,summary,caveat,command,stdout)

# %% ../nbs/03_ant.ipynb #d8ce7eef
def prepare_compaction(ref, cwd='.', policy=compact_policy, enc=None):
    "Prepare an incremental synthetic compaction without writing it"
    cwd = Path(cwd).expanduser()
    sid,path = resolve_session(ref, cwd)
    recs = load_sess(sid, cwd)
    prior,new_recs = split_compaction(recs)
    msgs = recs2chat(strip_think(new_recs))
    if not msgs: raise ValueError(f'No new messages to compact in {sid}')
    new_chat = compact_chat(msgs, enc=enc, last_n=5, **policy)
    new_full = compact_chat(msgs, enc=enc, **{k:10**9 for k in policy})
    chat,full = join_compacts(prior,new_chat),join_compacts(prior,new_full)
    content = compact_content(chat, path)
    pre_toks,post_toks = len_toks(full, enc),len_toks(content, enc)
    name = next((r.customTitle for r in reversed(recs) if r.type=='custom-title'), None)
    return AttrDict(sid=sid,name=name,cwd=cwd,path=path,records=compact_records(recs,content,pre_toks,post_toks),
        prior=prior,new_chat=new_chat,chat=chat,full=full,content=content,pre_toks=pre_toks,post_toks=post_toks)

# %% ../nbs/03_ant.ipynb #20acff2d
def append_compaction(compaction):
    "Append a prepared compaction and restore its session name"
    with Path(compaction.path).open('a') as f: f.writelines(xdumps(o)+'\n' for o in compaction.records)
    if compaction.name: name_sess(compaction.sid, compaction.name, compaction.cwd)
    return compaction.path

# %% ../nbs/03_ant.ipynb #448de8f6
def compact_session(ref, cwd='.', policy=compact_policy, enc=None):
    "Generate and append a synthetic session compaction"
    compaction = prepare_compaction(ref, cwd, policy, enc)
    append_compaction(compaction)
    return compaction

# %% ../nbs/03_ant.ipynb #8e9ed801
async def run_locked_agent(
    sysp:str, # Protocol for the child agent, as its system prompt
    prompt:str, # The task instance, e.g. a repo path
    allowed:list, # Permission rules, e.g. [r'Bash(/path/step1.sh *)']
    model:str='sonnet', # Model alias or full id
    max_turns:int=15, # Turn budget for the child
    timeout:int=600, # Seconds before the child is cancelled and killed
    cwd=None, # Directory the child works in; fastclaude's isolated work dir if None
):
    "Run a bare headless agent locked to `allowed` commands, returning (report, raw events)"
    tools = sorted({m[0] for r in allowed if (m:=re.match(r'\w+', r))})
    run = astream([Msg('user', [Text(prompt)])], model=model, system=sysp, cwd=cwd,
        native_tools=tools, allowed=allowed, setting_sources=(), max_turns=max_turns)
    evs = []
    async def _go():
        async for m in run: evs.append(m)
    await asyncio.wait_for(_go(), timeout)
    txts = [b['text'] for e in evs if e.get('type')=='assistant' for b in e['message']['content'] if b.get('type')=='text']
    return (txts[-1] if txts else None), evs

