"""Read, write, and build Claude Code session transcripts

Docs: https://AnswerDotAI.github.io/llmsurgery/ant.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_ant.ipynb.

# %% auto #0
__all__ = ['SESSIONS', 'CC_VERSION', 'sess_dir', 'cur_sess', 'sess_file', 'canon', 'stable_uuid', 'mk_rec', 'save_sess',
           'append_sess', 'msgs2recs', 'mk_tu', 'mk_tr', 'tool_turn', 'load_sess', 'sess_thread', 'rec_txt',
           'conv_recs', 'rec_role', 'SessHits', 'sess_search', 'show_recs', 'strip_think', 'trunc_tools', 'reid_recs',
           'fork_sess', 'dlg2msgs', 'dlg2sess', 'recs2msgs', 'msgs2dlg', 'sess2dlg']

# %% ../nbs/03_ant.ipynb #09dc6bf6
import base64, json, os, re, uuid
from datetime import datetime, timezone
from fastcore.utils import *
from fastllm.anthropic import denorm_msgs
from fastllm.chat import Msg, Part, PartType, mk_msg, hist2fmt, data_url
from .hist import dlg2canon
from .dialog import *

# %% ../nbs/03_ant.ipynb #66bb9972
SESSIONS = Path.home()/'.claude'/'projects'

def sess_dir(
    cwd=None, # Project directory; the current directory if None
):
    "The folder where Claude Code keeps session transcripts for the project at `cwd`"
    return SESSIONS/re.sub(r'[^a-zA-Z0-9]', '-', str(Path(cwd or '.').resolve()))

# %% ../nbs/03_ant.ipynb #a86a78a2
def cur_sess(
    cwd=None, # Project directory; the current directory if None
):
    "The current conversation's session id: the most recent transcript for the project at `cwd`, else the advertised id"
    try: return max(sess_dir(cwd).glob('*.jsonl'), key=lambda p: p.stat().st_mtime).stem
    except ValueError: return os.environ.get('CLAUDE_CODE_SESSION_ID')

# %% ../nbs/03_ant.ipynb #d031edb9
def sess_file(
    sid=None, # Session id; `cur_sess(cwd)` if None
    cwd=None, # Project directory; the current directory, then all projects, if None
):
    "Path to the transcript of session `sid` for the project at `cwd`"
    sid = sid or cur_sess(cwd)
    p = sess_dir(cwd)/f'{sid}.jsonl'
    if cwd is not None or p.exists(): return p
    return first(SESSIONS.glob(f'*/{sid}.jsonl')) or p

# %% ../nbs/03_ant.ipynb #5850201a
CC_VERSION = '2.1.206'

def canon(o):
    "Canonical compact JSON for `o`, key-sorted, for stable hashing"
    return json.dumps(o, sort_keys=True, separators=(',', ':'), ensure_ascii=False)

def stable_uuid(s):
    "A uuid deterministically derived from string `s`"
    return str(uuid.uuid5(uuid.NAMESPACE_URL, s))

# %% ../nbs/03_ant.ipynb #aec44130
def _now(): return datetime.now(timezone.utc).strftime(r'%Y-%m-%dT%H:%M:%S.%f')[:-3]+'Z'

def _txts(o, skip=()):
    if isinstance(o, str): yield o
    elif isinstance(o, dict): yield from (t for k,v in o.items() if k not in skip for t in _txts(v, skip))
    elif is_listy(o): yield from (t for x in o for t in _txts(x, skip))

def _est_toks(o):
    "Rule-of-thumb token estimate for every string in `o`: words * 1.5"
    return int(sum(len(s.split()) for s in _txts(o))*1.5)

# %% ../nbs/03_ant.ipynb #9da9f61e
def mk_rec(
    role, # 'user' or 'assistant'
    content, # A string, or a list of content blocks
    cwd='.', # Project directory recorded in the envelope
    uid=None, # Record uuid; random if None
    ts=None, # ISO8601 timestamp; the current time if None
    model='claude-sonnet-4-6', # Recorded in assistant API metadata; None omits it, so resume uses the user's default
    input_toks=0, # `input_tokens` recorded in assistant usage, e.g. an estimate of the context so far
    **kwargs, # Extra or overriding envelope fields, e.g. `isCompactSummary=True`
):
    "A transcript record for one conversation message, ready for `save_sess`"
    uid = uid or str(uuid.uuid4())
    if role=='user' and isinstance(content, list) and len(content)==1 and content[0].get('type')=='text': content = content[0]['text']
    msg = dict(type='message', role=role, content=content)
    r = dict(type=role, uuid=uid, parentUuid=None, sessionId=None, timestamp=ts or _now(), cwd=str(Path(cwd).resolve()),
        version=CC_VERSION, gitBranch='HEAD', isSidechain=False, userType='external', permissionMode='default', message=msg)
    if role=='assistant':
        tu = isinstance(content, list) and any(isinstance(b, dict) and b.get('type')=='tool_use' for b in content)
        r['requestId'] = 'req_'+stable_uuid(f'{uid}:req').replace('-', '')[:24]
        usage = dict(input_tokens=input_toks, output_tokens=_est_toks(content), cache_creation_input_tokens=0, cache_read_input_tokens=0)
        msg.update(id='msg_'+stable_uuid(f'{uid}:msg').replace('-', '')[:24],
            stop_reason='tool_use' if tu else 'end_turn', stop_sequence=None, stop_details=None, usage=usage)
        if model: msg['model'] = model
    return dict(r, **kwargs)

# %% ../nbs/03_ant.ipynb #ba9f2c9f
def save_sess(
    recs, # Records in conversation order, e.g. from `mk_rec`
    sid=None, # Session id; a fresh uuid if None
    cwd=None, # Project directory; the current directory if None
    ts=None, # If given, stamp every record's timestamp: True for the current time, or an ISO8601 string
):
    "Chain `recs`, write them as session `sid` for the project at `cwd`, and return `sid`"
    sid,prev = sid or str(uuid.uuid4()),None
    for r in recs:
        r['sessionId'],r['parentUuid'],prev = sid,prev,r['uuid']
        if ts: r['timestamp'] = _now() if ts is True else ts
        if 'session_id' in r: r['session_id'] = sid
    f = sess_file(sid, cwd or '.')
    f.parent.mkdir(parents=True, exist_ok=True)
    f.write_text(''.join(json.dumps(r)+'\n' for r in recs))
    return sid

# %% ../nbs/03_ant.ipynb #c161a097
def append_sess(
    recs, # Records to append, e.g. a munged template round
    sid=None, # Session to append to; `cur_sess()` if None
    cwd=None, # Project directory; the current directory if None
    ts=None, # If given, stamp each appended record's timestamp: True for the current time, or an ISO8601 string
):
    "Chain `recs` onto the tail of session `sid` and append them to its transcript, returning `sid`"
    sid = sid or cur_sess(cwd)
    prev = last(r['uuid'] for r in load_sess(sid, cwd) if 'uuid' in r)
    for r in recs:
        r['sessionId'],r['parentUuid'],prev = sid,prev,r['uuid']
        if ts: r['timestamp'] = _now() if ts is True else ts
        if 'session_id' in r: r['session_id'] = sid
    with sess_file(sid, cwd).open('a') as f: f.writelines(json.dumps(r)+'\n' for r in recs)
    return sid

# %% ../nbs/03_ant.ipynb #53b019df
def msgs2recs(
    msgs, # Anthropic-style messages: dicts with `role` and `content`
    key='', # Salt: the same messages and key give the same ids
    cwd='.', # Project directory recorded in the envelopes
    ts='2026-01-01T00:00:00.000Z', # Timestamp for every record
    model='claude-sonnet-4-6', # Recorded in assistant API metadata; None omits it, so resume uses the user's default
    **kwargs, # Extra envelope fields for every record, e.g. `entrypoint`
):
    "Deterministic transcript records for `msgs`, one record per message"
    out,tot = [],0
    for i,m in enumerate(msgs):
        out.append(mk_rec(m['role'], m['content'], cwd=cwd, uid=stable_uuid(f'{key}:{i}:{canon(m)}'), ts=ts, model=model, input_toks=tot, **kwargs))
        tot += _est_toks(m['content'])
    return out

# %% ../nbs/03_ant.ipynb #fb2e37dc
def mk_tu(
    name, # Tool name, as the transcript records it
    input=None, # Tool arguments
    tid=None, # tool_use id; random if None
):
    "A `tool_use` content block"
    return dict(type='tool_use', id=tid or 'toolu_'+uuid.uuid4().hex[:24], name=name, input=input or {})

def mk_tr(
    tu, # The `tool_use` block being answered
    content, # The tool's output
):
    "The `tool_result` content block answering `tu`"
    return dict(type='tool_result', tool_use_id=tu['id'], content=content)

def tool_turn(
    prompt, # The user request
    name, # Tool name
    input, # Tool arguments
    output, # Tool result
    answer, # The assistant's closing text
    **kwargs, # Passed to each `mk_rec`, e.g. `cwd`
):
    "A complete synthetic tool-use turn, as four records ready for `save_sess`"
    tu = mk_tu(name, input)
    return [mk_rec('user', prompt, **kwargs), mk_rec('assistant', [tu], **kwargs),
        mk_rec('user', [mk_tr(tu, output)], **kwargs), mk_rec('assistant', [dict(type='text', text=answer)], **kwargs)]

# %% ../nbs/03_ant.ipynb #e3ef0c32
def load_sess(
    sid=None, # Session id; the current session if None
    cwd=None, # Project directory; the current directory if None
):
    "The records of session `sid`, as an `L` of attribute-access dicts"
    return L(dict2obj(json.loads(l)) for l in sess_file(sid, cwd).read_text().splitlines())

# %% ../nbs/03_ant.ipynb #a5f38b3d
def sess_thread(
    recs, # Session records, e.g. from `load_sess`
):
    "The records on the active conversation chain, walking `parentUuid` back from the last record"
    byid = {r.uuid:r for r in recs if 'uuid' in r}
    cur,res = recs.filter(lambda r: 'uuid' in r)[-1],[]
    while cur is not None:
        res.append(cur)
        cur = byid.get(cur.get('parentUuid'))
    return L(reversed(res))

# %% ../nbs/03_ant.ipynb #5bfa0829
def rec_txt(
    r, # A session record
):
    "Every readable string in `r`'s message content, joined, for finding records by text"
    return '\n'.join(_txts(obj2dict(r).get('message', {}).get('content', ''), skip=('type','id','tool_use_id','signature')))

# %% ../nbs/03_ant.ipynb #f9d47bbc
def conv_recs(
    recs, # Session records, e.g. from `load_sess`
):
    "Just the records carrying conversation messages, dropping Claude Code's bookkeeping"
    return L(r for r in recs if r.get('type') in ('user','assistant') and 'message' in r)

def rec_role(
    r, # A session record
):
    "The conversational role of `r`: a user record carrying tool results counts as `tool`"
    r = obj2dict(r)
    c = r['message']['content']
    if r['type']=='user' and isinstance(c, list) and any(b.get('type')=='tool_result' for b in c): return 'tool'
    return r['type']

# %% ../nbs/03_ant.ipynb #defb1a03
def _preview(t, m, maxlen):
    h = maxlen//2
    s,e = max(0, m.start()-h), min(len(t), m.end()+h)
    return ('…' if s else '') + t[s:e].replace('\n',' ') + ('…' if e<len(t) else '')

class SessHits(list):
    "Search hits with a match-centered preview per line"
    def __repr__(self): return '\n'.join(f"{h.i:5} {h.role:9} {h.ts[:16]} {h.preview}" for h in self)

def sess_search(
    pat, # Regex to find in conversation text
    sid=None, # Session id; the current session if None
    cwd=None, # Project directory; the current directory if None
    maxlen=160, # Preview characters shown around a hit's first match
):
    "Search every conversation record of a session, returning `SessHits` with the records on `.recs`"
    recs = conv_recs(load_sess(sid, cwd))
    res = SessHits()
    for i,r in enumerate(recs):
        if m := re.search(pat, t:=rec_txt(r)): res.append(AttrDict(i=i, role=rec_role(r), ts=r['timestamp'], preview=_preview(t, m, maxlen), rec=r))
    res.recs = recs
    return res

# %% ../nbs/03_ant.ipynb #58f5cf47
def show_recs(
    recs, # Session records, e.g. a slice of `SessHits.recs`
    mx=500, # Characters of text shown per record
):
    "A readable transcript of the conversation records in `recs`"
    def _s(r):
        t = rec_txt(r)
        if len(t)>mx: t = t[:mx]+f'…[+{len(t)-mx} chars]'
        return f"--- {rec_role(r)} {r['timestamp'][:19]} ---\n{t}"
    return PrettyString('\n'.join(_s(r) for r in conv_recs(recs)))

# %% ../nbs/03_ant.ipynb #9e265e88
def strip_think(
    recs, # Session records
):
    "Drop records whose message content is only `thinking` blocks; resume does not need them"
    def _keep(r):
        c = r.get('message', {}).get('content', '')
        return isinstance(c, str) or not all(b.get('type')=='thinking' for b in c)
    return L(recs).filter(_keep)

# %% ../nbs/03_ant.ipynb #a56fc348
def _trunc_deep(o, mx):
    if isinstance(o, str): return o if len(o)<=mx else o[:mx]+f'…[+{len(o)-mx} chars]'
    if isinstance(o, dict): return {k:_trunc_deep(v, mx) for k,v in o.items()}
    if is_listy(o): return [_trunc_deep(x, mx) for x in o]
    return o

def trunc_tools(
    recs, # Session records
    mx=2000, # Maximum characters per string in tool inputs and results
):
    "Copies of `recs` with strings in tool_use inputs and tool_result content truncated to `mx` characters"
    recs = [obj2dict(r) for r in recs]
    for r in recs:
        c = r.get('message', {}).get('content', '')
        if isinstance(c, str): continue
        for b in c:
            if b.get('type')=='tool_use': b['input'] = _trunc_deep(b.get('input', {}), mx)
            elif b.get('type')=='tool_result' and 'content' in b: b['content'] = _trunc_deep(b['content'], mx)
    return L(recs)

# %% ../nbs/03_ant.ipynb #7ffe1bb4
def reid_recs(
    recs, # Records in conversation order
    key='', # Salt: the same records and key give the same ids
    ts=None, # If given, set every record's timestamp to this
):
    "Deterministically re-derive record uuids, tool_use ids, and API metadata, so one capture gives one file"
    recs,ids = [obj2dict(r) for r in recs],{}
    for i,r in enumerate(recs):
        c = r.get('message', {}).get('content', '')
        if not isinstance(c, str):
            for j,b in enumerate(c):
                if b.get('type')=='tool_use':
                    nid = 'toolu_'+stable_uuid(f'{key}:{i}:{j}').replace('-', '')[:24]
                    ids[b['id']],b['id'] = nid,nid
                elif b.get('type')=='tool_result' and b.get('tool_use_id') in ids: b['tool_use_id'] = ids[b['tool_use_id']]
        uid = stable_uuid(f'{key}:{i}')
        if 'uuid' in r: ids[r['uuid']] = uid
        r['uuid'] = uid
        if ts: r['timestamp'] = ts
        if r.get('type')=='assistant':
            r['requestId'] = 'req_'+stable_uuid(f'{uid}:req').replace('-', '')[:24]
            r['message']['id'] = 'msg_'+stable_uuid(f'{uid}:msg').replace('-', '')[:24]
    for r in recs:
        for k,v in r.items():
            if isinstance(v, str) and v in ids: r[k] = ids[v]
    return L(recs)

# %% ../nbs/03_ant.ipynb #6db09ecc
def fork_sess(
    sid=None, # Session id to fork; `cur_sess()` if None
    cwd=None, # Project directory; passed to `sess_file` via `load_sess`
    mx=None, # If given, truncate tool input/output strings to `mx` characters
    think=True, # Keep thinking records?
    key=None, # If given, record and session ids re-derive deterministically from this salt
):
    "Write a munged copy of session `sid` under a fresh id, returning the new id to resume"
    recs = sess_thread(load_sess(sid, cwd))
    if not think: recs = strip_think(recs)
    if mx: recs = trunc_tools(recs, mx)
    if key: recs = reid_recs(recs, key)
    return save_sess(list(recs), stable_uuid(key) if key else None, cwd)

# %% ../nbs/03_ant.ipynb #7b8d57fa
def dlg2msgs(
    dlg, # A `Dialog`, ending with a prompt
    aim_info=None, # Model capability dict for media handling; images enabled if None
):
    "Anthropic-style messages for `dlg`, with each reply's tool calls recovered as real blocks"
    return denorm_msgs(dlg2canon(dlg, aim_info))

def dlg2sess(
    dlg, # The dialog to convert
    cwd=None, # Project directory for the session; the current directory if None
    key='dlg2sess', # Salt for deterministic record ids
    aim_info=None, # Model capability dict; images enabled if None
):
    "Write `dlg` as a Claude Code session for the project at `cwd`, returning the session id to resume"
    recs = msgs2recs(dlg2msgs(dlg, aim_info), key=key, cwd=str(Path(cwd or '.').resolve()))
    return save_sess(recs, stable_uuid(f'{key}:{dlg.name}'), cwd)

# %% ../nbs/03_ant.ipynb #16af5ac6
def _tr_txt(b):
    c = b.get('content', '')
    if isinstance(c, str): return c
    if any(x.get('type') not in ('text','tool_reference') for x in c): raise ValueError('unsupported tool_result block')
    return '\n'.join(x['text'] if x['type']=='text' else f"<tool_reference tool=\"{x['tool_name']}\"/>" for x in c)

def _norm_user(content):
    if isinstance(content, str): return mk_msg(content)
    items = []
    for b in content:
        if b['type']=='text': items.append(b['text'])
        elif b['type']=='image': items.append(base64.b64decode(b['source']['data']))
        else: raise ValueError(f"unsupported user block: {b['type']}")
    return mk_msg(items)

def recs2msgs(
    recs, # Session records, e.g. from `load_sess`
):
    "Canonical fastllm messages for the conversation records in `recs`"
    msgs,names = [],{}
    for r in recs:
        r = obj2dict(r)
        if r.get('type') not in ('user','assistant'): continue
        c = r['message']['content']
        if isinstance(c, str) and r['type']=='assistant': c = [dict(type='text', text=c)]
        if r['type']=='assistant':
            parts = []
            for b in c:
                if b['type']=='text': parts.append(Part(type=PartType.text, text=b['text']))
                elif b['type']=='thinking': parts.append(Part(type=PartType.thinking, text=b.get('thinking','')))
                elif b['type']=='tool_use':
                    names[b['id']] = b['name']
                    parts.append(Part(type=PartType.tool_use, data=dict(id=b['id'], name=b['name'], arguments=b.get('input', {}))))
                else: raise ValueError(f"unsupported assistant block: {b['type']}")
            msgs.append(Msg(role='assistant', content=parts))
        elif rec_role(r)=='tool':
            if not all(b.get('type')=='tool_result' for b in c): raise ValueError('record mixes tool_result with other blocks')
            msgs.append(Msg(role='tool', content=[Part(type=PartType.tool_result, text=_tr_txt(b),
                data=dict(id=b['tool_use_id'], name=names.get(b['tool_use_id']))) for b in c]))
        else: msgs.append(_norm_user(c))
    return msgs

# %% ../nbs/03_ant.ipynb #ac13833a
def msgs2dlg(
    msgs, # Canonical messages, e.g. from `recs2msgs`
    name, # Dialog name
    cls=Dialog, # Dialog class to create
    mx=2000, # Maximum characters per rendered tool input/output string; None disables truncation (see `hist2fmt`)
):
    "A dialog for `msgs`: one prompt per user turn, replies rendered in the format `fmt2hist` parses"
    dlg,turns = cls(name),[]
    for m in msgs:
        if m.role=='user': turns.append((m,[]))
        elif turns: turns[-1][1].append(m)
        else: raise ValueError('msgs must start with a user message')
    for u,rs in turns:
        segs,atts = [],[]
        for p in u.content:
            if p.type==PartType.text: segs.append(p.text)
            elif p.type==PartType.input_image:
                mime,data = data_url(p.text)
                atts.append(Attachment(base64.b64decode(data), mime))
                segs.append(f'![](attachment:{atts[-1].id})')
            else: raise ValueError(f'unsupported user part: {p.type}')
        dlg.mk_message('\n\n'.join(segs), msg_type=sprompt, output=hist2fmt(rs, mx=mx), attachments=atts)
    return dlg

# %% ../nbs/03_ant.ipynb #abc4a08a
def sess2dlg(
    sid=None, # Session id; `cur_sess()` if None
    cwd=None, # Project directory; passed to `sess_file` via `load_sess`
    name=None, # Dialog name; the session id if None
    mx=2000, # Maximum characters per rendered tool input/output string; None disables truncation (see `hist2fmt`)
):
    "The conversation of session `sid` as a dialog, one prompt per user turn"
    recs = strip_think(sess_thread(load_sess(sid, cwd)))
    return msgs2dlg(recs2msgs(recs), name or sid or cur_sess(), mx=mx)
