"""Read, write, and build Claude Code session transcripts

Docs: https://AnswerDotAI.github.io/llmsurgery/ant.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_ant.ipynb.

# %% auto #0
__all__ = ['SESSIONS', 'CC_VERSION', 'sess_dir', 'cur_sess', 'sess_file', 'load_recs', 'sess_thread', 'rec_txt', 'sess_id',
           'canon', 'stable_uuid', 'mk_rec', 'save_sess', 'append_sess', 'msgs2recs', 'mk_tu', 'mk_tr', 'tool_turn',
           'load_sess', 'conv_recs', 'rec_role', 'SessHits', 'sess_search', 'show_recs', 'PromptHist', 'prompt_hist',
           'is_think_rec', 'strip_think', 'trunc_tools', 'reid_recs', 'name_sess', 'sess_by_name', 'fork_sess',
           'dlg2msgs', 'dlg2sess', 'recs2chat', 'chat2dlg', 'sess2dlg', 'resolve_session', 'split_compaction',
           'sess_meta', 'compact_records', 'prepare_compaction', 'append_compaction', 'compact_session']

# %% ../nbs/03_ant.ipynb #09dc6bf6
import base64, json, os, re, uuid
from datetime import datetime, timezone
from fastcore.utils import *
from fastllm.anthropic import denorm_msgs
from fastllm.chat import Msg, Part, PartType, mk_msg, hist2fmt, data_url
from .hist import dlg2chat
from .dialog import *
from .compact import *

# %% ../nbs/03_ant.ipynb #66bb9972
SESSIONS = Path.home()/'.claude'/'projects'

def sess_dir(
    cwd=None, # Project directory; the current directory if None
):
    "The folder where Claude Code keeps session transcripts for the project at `cwd`"
    return SESSIONS/re.sub(r'[^a-zA-Z0-9]', '-', str(Path(cwd or '.').expanduser().resolve()))

# %% ../nbs/03_ant.ipynb #a86a78a2
def cur_sess(
    cwd=None, # Project directory; the current directory if None
):
    "The current conversation's session id: the most recent transcript for the project at `cwd`, else the advertised id"
    try: return max(sess_dir(cwd).glob('*.jsonl'), key=lambda p: p.stat().st_mtime).stem
    except ValueError: return os.environ.get('CLAUDE_CODE_SESSION_ID')

# %% ../nbs/03_ant.ipynb #d031edb9
def sess_file(
    sid=None, # Session id; `cur_sess(cwd)` if None
    cwd=None, # Project directory; the current directory, then all projects, if None
):
    "Path to the transcript of session `sid` for the project at `cwd`"
    sid = sid or cur_sess(cwd)
    p = sess_dir(cwd)/f'{sid}.jsonl'
    if cwd is not None or p.exists(): return p
    return first(SESSIONS.glob(f'*/{sid}.jsonl')) or p

# %% ../nbs/03_ant.ipynb #2df63fe4
def load_recs(path):
    "Session records read directly from JSONL `path`"
    return L(dict2obj(json.loads(l)) for l in Path(path).read_text().splitlines())

# %% ../nbs/03_ant.ipynb #5e7dba33
def sess_thread(
    recs, # Session records, e.g. from `load_sess`
):
    "The records on the active conversation chain, walking `parentUuid` back from the last record"
    recs = L(r for r in recs if r.get('type') in ('user','assistant','attachment','system') and r.get('uuid'))
    byid = {r.uuid:r for r in recs}
    cur,res = recs[-1],[]
    while cur is not None:
        res.append(cur)
        cur = byid.get(cur.get('parentUuid'))
    return L(reversed(res))

# %% ../nbs/03_ant.ipynb #a644634a
def _txts(o, skip=()):
    if isinstance(o, str): yield o
    elif isinstance(o, dict): yield from (t for k,v in o.items() if k not in skip for t in _txts(v, skip))
    elif is_listy(o): yield from (t for x in o for t in _txts(x, skip))

# %% ../nbs/03_ant.ipynb #f89285a6
def rec_txt(
    r, # A session record
):
    "Every readable string in `r`'s message content, joined, for finding records by text"
    return '\n'.join(_txts(obj2dict(r).get('message', {}).get('content', ''), skip=('type','id','tool_use_id','signature')))

# %% ../nbs/03_ant.ipynb #d5aff5ad
def sess_id(recs):
    "The session id in transcript records `recs`"
    return first(r.get('sessionId') for r in recs if r.get('sessionId'))

# %% ../nbs/03_ant.ipynb #5850201a
CC_VERSION = '2.1.206'

def canon(o):
    "Canonical compact JSON for `o`, key-sorted, for stable hashing"
    return json.dumps(o, sort_keys=True, separators=(',', ':'), ensure_ascii=False)

def stable_uuid(s):
    "A uuid deterministically derived from string `s`"
    return str(uuid.uuid5(uuid.NAMESPACE_URL, s))

# %% ../nbs/03_ant.ipynb #66514ea6
def _now(): return datetime.now(timezone.utc).strftime(r'%Y-%m-%dT%H:%M:%S.%f')[:-3]+'Z'

def _est_toks(o):
    "Rule-of-thumb token estimate for every string in `o`: words * 1.5"
    return int(sum(len(s.split()) for s in _txts(o))*1.5)

# %% ../nbs/03_ant.ipynb #9da9f61e
def mk_rec(
    role, # 'user' or 'assistant'
    content, # A string, or a list of content blocks
    cwd='.', # Project directory recorded in the envelope
    uid=None, # Record uuid; random if None
    ts=None, # ISO8601 timestamp; the current time if None
    model='claude-sonnet-4-6', # Recorded in assistant API metadata; None omits it, so resume uses the user's default
    input_toks=0, # `input_tokens` recorded in assistant usage, e.g. an estimate of the context so far
    **kwargs, # Extra or overriding envelope fields, e.g. `isCompactSummary=True`
):
    "A transcript record for one conversation message, ready for `save_sess`"
    uid = uid or str(uuid.uuid4())
    if role=='user' and isinstance(content, list) and len(content)==1 and content[0].get('type')=='text': content = content[0]['text']
    msg = dict(type='message', role=role, content=content)
    r = dict(type=role, uuid=uid, parentUuid=None, sessionId=None, timestamp=ts or _now(), cwd=str(Path(cwd).expanduser().resolve()),
        version=CC_VERSION, gitBranch='HEAD', isSidechain=False, userType='external', permissionMode='default', message=msg)
    if role=='assistant':
        tu = isinstance(content, list) and any(isinstance(b, dict) and b.get('type')=='tool_use' for b in content)
        r['requestId'] = 'req_'+stable_uuid(f'{uid}:req').replace('-', '')[:24]
        usage = dict(input_tokens=input_toks, output_tokens=_est_toks(content), cache_creation_input_tokens=0, cache_read_input_tokens=0)
        msg.update(id='msg_'+stable_uuid(f'{uid}:msg').replace('-', '')[:24],
            stop_reason='tool_use' if tu else 'end_turn', stop_sequence=None, stop_details=None, usage=usage)
        if model: msg['model'] = model
    return dict(r, **kwargs)

# %% ../nbs/03_ant.ipynb #ba9f2c9f
def save_sess(
    recs, # Records in conversation order, e.g. from `mk_rec`
    sid=None, # Session id; a fresh uuid if None
    cwd=None, # Project directory; the current directory if None
    ts=None, # If given, stamp every record's timestamp: True for the current time, or an ISO8601 string
):
    "Chain `recs`, write them as session `sid` for the project at `cwd`, and return `sid`"
    sid,prev = sid or str(uuid.uuid4()),None
    for r in recs:
        r['sessionId'],r['parentUuid'],prev = sid,prev,r['uuid']
        if ts: r['timestamp'] = _now() if ts is True else ts
        if 'session_id' in r: r['session_id'] = sid
    f = sess_file(sid, cwd or '.')
    f.parent.mkdir(parents=True, exist_ok=True)
    f.write_text(''.join(xdumps(r)+'\n' for r in recs))
    return sid

# %% ../nbs/03_ant.ipynb #c161a097
def append_sess(
    recs, # Records to append, e.g. a munged template round
    sid=None, # Session to append to; `cur_sess()` if None
    cwd=None, # Project directory; the current directory if None
    ts=None, # If given, stamp each appended record's timestamp: True for the current time, or an ISO8601 string
):
    "Chain `recs` onto the tail of session `sid` and append them to its transcript, returning `sid`"
    sid = sid or cur_sess(cwd)
    prev = last(r['uuid'] for r in load_sess(sid, cwd) if 'uuid' in r)
    for r in recs:
        r['sessionId'],r['parentUuid'],prev = sid,prev,r['uuid']
        if ts: r['timestamp'] = _now() if ts is True else ts
        if 'session_id' in r: r['session_id'] = sid
    with sess_file(sid, cwd).open('a') as f: f.writelines(xdumps(r)+'\n' for r in recs)
    return sid

# %% ../nbs/03_ant.ipynb #53b019df
def msgs2recs(
    msgs, # Anthropic-style messages: dicts with `role` and `content`
    key='', # Salt: the same messages and key give the same ids
    cwd='.', # Project directory recorded in the envelopes
    ts='2026-01-01T00:00:00.000Z', # Timestamp for every record
    model='claude-sonnet-4-6', # Recorded in assistant API metadata; None omits it, so resume uses the user's default
    **kwargs, # Extra envelope fields for every record, e.g. `entrypoint`
):
    "Deterministic transcript records for `msgs`, one record per message"
    out,tot = [],0
    for i,m in enumerate(msgs):
        out.append(mk_rec(m['role'], m['content'], cwd=cwd, uid=stable_uuid(f'{key}:{i}:{canon(m)}'), ts=ts, model=model, input_toks=tot, **kwargs))
        tot += _est_toks(m['content'])
    return out

# %% ../nbs/03_ant.ipynb #fb2e37dc
def mk_tu(
    name, # Tool name, as the transcript records it
    input=None, # Tool arguments
    tid=None, # tool_use id; random if None
):
    "A `tool_use` content block"
    return dict(type='tool_use', id=tid or 'toolu_'+uuid.uuid4().hex[:24], name=name, input=input or {})

def mk_tr(
    tu, # The `tool_use` block being answered
    content, # The tool's output
):
    "The `tool_result` content block answering `tu`"
    return dict(type='tool_result', tool_use_id=tu['id'], content=content)

def tool_turn(
    prompt, # The user request
    name, # Tool name
    input, # Tool arguments
    output, # Tool result
    answer, # The assistant's closing text
    **kwargs, # Passed to each `mk_rec`, e.g. `cwd`
):
    "A complete synthetic tool-use turn, as four records ready for `save_sess`"
    tu = mk_tu(name, input)
    return [mk_rec('user', prompt, **kwargs), mk_rec('assistant', [tu], **kwargs),
        mk_rec('user', [mk_tr(tu, output)], **kwargs), mk_rec('assistant', [dict(type='text', text=answer)], **kwargs)]

# %% ../nbs/03_ant.ipynb #e3ef0c32
def load_sess(
    sid=None, # Session id; the current session if None
    cwd=None, # Project directory; the current directory if None
):
    "The records of session `sid`, as an `L` of attribute-access dicts"
    return load_recs(sess_file(sid, cwd))

# %% ../nbs/03_ant.ipynb #f9d47bbc
def conv_recs(
    recs, # Session records, e.g. from `load_sess`
):
    "Just the records carrying conversation messages, dropping Claude Code's bookkeeping"
    return L(r for r in recs if r.get('type') in ('user','assistant') and 'message' in r)

def rec_role(
    r, # A session record
):
    "The conversational role of `r`: a user record carrying tool results counts as `tool`"
    r = obj2dict(r)
    c = r['message']['content']
    if r['type']=='user' and isinstance(c, list) and any(b.get('type')=='tool_result' for b in c): return 'tool'
    return r['type']

# %% ../nbs/03_ant.ipynb #defb1a03
def _preview(t, m, maxlen):
    h = maxlen//2
    s,e = max(0,m.start()-h),min(len(t),m.end()+h)
    return ('…' if s else '')+t[s:e].replace('\n',' ')+('…' if e<len(t) else '')

class SessHits(list):
    "Search hits with a match-centered preview per line"
    def __repr__(self): return '\n'.join(f"{h.i:5} {h.role:9} {h.ts[:16]} {h.preview}" for h in self)

def sess_search(
    pat, # Regex to find in conversation text
    sid=None, # Session id; the current session if None
    cwd=None, # Project directory; the current directory if None
    maxlen=160, # Preview characters shown around a hit's first match
    recs=None, # Already-loaded records; if given, `sid` and `cwd` are ignored
):
    "Search conversation records, returning `SessHits` with the records on `.recs`"
    recs = conv_recs(load_sess(sid,cwd) if recs is None else recs)
    res = SessHits()
    for i,r in enumerate(recs):
        if m := re.search(pat,t:=rec_txt(r)): res.append(AttrDict(i=i,role=rec_role(r),ts=r['timestamp'],preview=_preview(t,m,maxlen),rec=r))
    res.recs = recs
    return res

# %% ../nbs/03_ant.ipynb #58f5cf47
def show_recs(
    recs, # Session records, e.g. a slice of `SessHits.recs`
    mx=500, # Characters of text shown per record
    showall:bool=False, # Include bookkeeping records?
):
    "A readable transcript of records in `recs`; conversation records only unless `showall`"
    def _s(r):
        t = rec_txt(r)
        if len(t)>mx: t = t[:mx]+f'…[+{len(t)-mx} chars]'
        role = rec_role(r) if r.get('type') in ('user','assistant') else ':'.join(filter(None,(r.get('type'),r.get('subtype'))))
        return f"--- {role} {r.get('timestamp','')[:19]} ---\n{t}"
    return PrettyString('\n'.join(_s(r) for r in (recs if showall else conv_recs(recs))))

# %% ../nbs/03_ant.ipynb #343ac533
class PromptHist(list):
    "Prompt-history rows in local time, one line per prompt"
    def __repr__(self): return '\n'.join(f"{h.ts:%Y-%m-%d %H:%M} {Path(h.project).name:>12} {h.display.replace(chr(10),' ')[:120]}" for h in self)

def prompt_hist(
    project=None, # Only prompts for the project at this directory; all projects if None
    since=None, # Only prompts at or after this datetime or ISO string; a TZ-less string is on the same local clock as the returned times, Z/offset strings are converted
    pat=None, # Only prompts whose text matches this regex
    path=None, # History file; Claude Code's own (`~/.claude/history.jsonl`) if None
):
    "Claude Code's global prompt history, oldest first: every prompt typed on this machine, kept even when its transcript is gone"
    rows = [json.loads(l) for l in Path(path or Path.home()/'.claude'/'history.jsonl').read_text().splitlines()]
    res = [AttrDict(ts=datetime.fromtimestamp(r['timestamp']/1000), project=r.get('project',''), display=r.get('display',''))
           for r in rows if isinstance(r.get('timestamp'), (int,float))]
    if project: res = [r for r in res if r.project==str(Path(project).expanduser().resolve())]
    if isinstance(since, str): since = datetime.fromisoformat(since)
    if since and since.tzinfo: since = since.astimezone().replace(tzinfo=None)
    if since: res = [r for r in res if r.ts>=since]
    if pat: res = [r for r in res if re.search(pat, r.display)]
    return PromptHist(res)

# %% ../nbs/03_ant.ipynb #9e265e88
def is_think_rec(
    r, # Session record
):
    "Whether `r` is an assistant record containing only thinking blocks"
    c = nested_idx(r, 'message', 'content')
    return r.get('type')=='assistant' and is_listy(c) and bool(c) and all(b.get('type')=='thinking' for b in c)

def strip_think(
    recs, # Session records
):
    "Drop records whose message content is only `thinking` blocks; resume does not need them"
    return L(recs).filter(lambda r:not is_think_rec(r))

# %% ../nbs/03_ant.ipynb #a56fc348
def _trunc_deep(o, mx):
    if isinstance(o, str): return o if len(o)<=mx else o[:mx]+f'…[+{len(o)-mx} chars]'
    if isinstance(o, dict): return {k:_trunc_deep(v, mx) for k,v in o.items()}
    if is_listy(o): return [_trunc_deep(x, mx) for x in o]
    return o

def trunc_tools(
    recs, # Session records
    mx=2000, # Maximum characters per string in tool inputs and results
):
    "Copies of `recs` with strings in tool_use inputs and tool_result content truncated to `mx` characters"
    recs = [obj2dict(r) for r in recs]
    for r in recs:
        c = r.get('message', {}).get('content', '')
        if isinstance(c, str): continue
        for b in c:
            if b.get('type')=='tool_use': b['input'] = _trunc_deep(b.get('input', {}), mx)
            elif b.get('type')=='tool_result' and 'content' in b: b['content'] = _trunc_deep(b['content'], mx)
    return L(recs)

# %% ../nbs/03_ant.ipynb #7ffe1bb4
def reid_recs(
    recs, # Records in conversation order
    key='', # Salt: the same records and key give the same ids
    ts=None, # If given, set every record's timestamp to this
):
    "Deterministically re-derive record uuids, tool_use ids, and API metadata, so one capture gives one file"
    recs,ids = [obj2dict(r) for r in recs],{}
    for i,r in enumerate(recs):
        c = r.get('message', {}).get('content', '')
        if not isinstance(c, str):
            for j,b in enumerate(c):
                if b.get('type')=='tool_use':
                    nid = 'toolu_'+stable_uuid(f'{key}:{i}:{j}').replace('-', '')[:24]
                    ids[b['id']],b['id'] = nid,nid
                elif b.get('type')=='tool_result' and b.get('tool_use_id') in ids: b['tool_use_id'] = ids[b['tool_use_id']]
        uid = stable_uuid(f'{key}:{i}')
        if 'uuid' in r: ids[r['uuid']] = uid
        r['uuid'] = uid
        if ts: r['timestamp'] = ts
        if r.get('type')=='assistant':
            r['requestId'] = 'req_'+stable_uuid(f'{uid}:req').replace('-', '')[:24]
            r['message']['id'] = 'msg_'+stable_uuid(f'{uid}:msg').replace('-', '')[:24]
    for r in recs:
        for k,v in r.items():
            if isinstance(v, str) and v in ids: r[k] = ids[v]
    return L(recs)

# %% ../nbs/03_ant.ipynb #58e65644
def name_sess(sid, name, cwd=None):
    "Name session `sid` and return it"
    recs = [dict(type='custom-title', customTitle=name, sessionId=sid), dict(type='agent-name', agentName=name, sessionId=sid)]
    with sess_file(sid, cwd).open('a') as f: f.writelines(xdumps(r)+'\n' for r in recs)
    return sid

# %% ../nbs/03_ant.ipynb #a6d54271
def sess_by_name(name, cwd='.'):
    "Find the first project session transcript with latest custom title `name`"
    for f in sess_dir(Path(cwd).expanduser()).glob('*.jsonl'):
        recs = map(json.loads, reversed(f.read_text().splitlines()))
        if first((r.get('customTitle') for r in recs if r.get('type')=='custom-title'))==name: return f

# %% ../nbs/03_ant.ipynb #6db09ecc
def fork_sess(
    sid=None, # Session id to fork; `cur_sess()` if None
    cwd=None, # Project directory; passed to `sess_file` via `load_sess`
    mx=None, # If given, truncate tool input/output strings to `mx` characters
    think=True, # Keep thinking records?
    key=None, # If given, record and session ids re-derive deterministically from this salt
    name=None, # Optional name for the new session
):
    "Write a munged copy of session `sid` under a fresh id, returning the new id to resume"
    recs = sess_thread(load_sess(sid, cwd))
    if not think: recs = strip_think(recs)
    if mx is not None: recs = trunc_tools(recs, mx)
    if key: recs = reid_recs(recs, key)
    sid = save_sess(list(recs), stable_uuid(key) if key else None, cwd)
    return name_sess(sid, name, cwd) if name else sid

# %% ../nbs/03_ant.ipynb #7b8d57fa
def dlg2msgs(
    dlg, # A `Dialog`, ending with a prompt
    aim_info=None, # Model capability dict for media handling; images enabled if None
):
    "Anthropic-style messages for `dlg`, with each reply's tool calls recovered as real blocks"
    return denorm_msgs(dlg2chat(dlg, aim_info))

def dlg2sess(
    dlg, # The dialog to convert
    cwd=None, # Project directory for the session; the current directory if None
    key='dlg2sess', # Salt for deterministic record ids
    aim_info=None, # Model capability dict; images enabled if None
):
    "Write `dlg` as a Claude Code session for the project at `cwd`, returning the session id to resume; tagged raw messages re-emit their original records"
    recs = msgs2recs(dlg2msgs(dlg, aim_info), key=key, cwd=str(Path(cwd or '.').expanduser().resolve()))
    raws,t = {},-1
    for m in dlg.messages:
        if m.msg_type==sprompt: t += 1
        elif m.msg_type==sraw and m.meta.get('rec_kind'): raws.setdefault(t, []).append(dict(m.meta['rec']))
    if raws:
        out,t = [],-1
        for r in recs:
            if r['type']=='user' and rec_role(r)!='tool':
                out += raws.get(t, [])
                t += 1
            out.append(r)
        out += raws.get(t, [])
        recs = out
    return save_sess(recs, stable_uuid(f'{key}:{dlg.name}'), cwd)

# %% ../nbs/03_ant.ipynb #16af5ac6
def _tr_txt(b):
    c = b.get('content', '')
    if isinstance(c, str): return c
    if any(x.get('type') not in ('text','tool_reference') for x in c): raise ValueError('unsupported tool_result block')
    return '\n'.join(x['text'] if x['type']=='text' else f"<tool_reference tool=\"{x['tool_name']}\"/>" for x in c)

def _norm_user(content):
    if isinstance(content, str): return mk_msg(content)
    items = []
    for b in content:
        if b['type']=='text': items.append(b['text'])
        elif b['type']=='image': items.append(base64.b64decode(b['source']['data']))
        else: raise ValueError(f"unsupported user block: {b['type']}")
    return mk_msg(items)

def recs2chat(
    recs, # Session records, e.g. from `load_sess`
):
    "Canonical fastllm messages for the conversation records in `recs`"
    msgs,names = [],{}
    for r in recs:
        r = obj2dict(r)
        if r.get('type') not in ('user','assistant'): continue
        c = r['message']['content']
        if isinstance(c, str) and r['type']=='assistant': c = [dict(type='text', text=c)]
        if r['type']=='assistant':
            parts = []
            for b in c:
                if b['type']=='text': parts.append(Part(type=PartType.text, text=b['text']))
                elif b['type']=='thinking': parts.append(Part(type=PartType.thinking, text=b.get('thinking','')))
                elif b['type']=='tool_use':
                    names[b['id']] = b['name']
                    parts.append(Part(type=PartType.tool_use, data=dict(id=b['id'], name=b['name'], arguments=b.get('input', {}))))
                else: raise ValueError(f"unsupported assistant block: {b['type']}")
            msgs.append(Msg(role='assistant', content=parts))
        elif rec_role(r)=='tool':
            if not all(b.get('type')=='tool_result' for b in c): raise ValueError('record mixes tool_result with other blocks')
            msgs.append(Msg(role='tool', content=[Part(type=PartType.tool_result, text=_tr_txt(b),
                data=dict(id=b['tool_use_id'], name=names.get(b['tool_use_id']))) for b in c]))
        else: msgs.append(_norm_user(c))
    return msgs

# %% ../nbs/03_ant.ipynb #ac13833a
def chat2dlg(
    msgs, # Canonical messages, e.g. from `recs2chat`
    name, # Dialog name
    cls=Dialog, # Dialog class to create
    mx=2000, # Maximum characters per rendered tool input/output string; None disables truncation (see `hist2fmt`)
):
    "A dialog for `msgs`: one prompt per user turn, replies rendered in the format `fmt2hist` parses"
    dlg,turns = cls(name),[]
    for m in msgs:
        if m.role=='user': turns.append((m,[]))
        elif turns: turns[-1][1].append(m)
        else: raise ValueError('msgs must start with a user message')
    for u,rs in turns:
        segs,atts = [],[]
        for p in u.content:
            if p.type==PartType.text: segs.append(p.text)
            elif p.type==PartType.input_image:
                mime,data = data_url(p.text)
                atts.append(Attachment(base64.b64decode(data), mime))
                segs.append(f'![](attachment:{atts[-1].id})')
            else: raise ValueError(f'unsupported user part: {p.type}')
        dlg.mk_message('\n\n'.join(segs), msg_type=sprompt, output=hist2fmt(rs, mx=mx), attachments=atts)
    return dlg

# %% ../nbs/03_ant.ipynb #abc4a08a
def sess2dlg(
    sid=None, # Session id; `cur_sess()` if None
    cwd=None, # Project directory; passed to `sess_file` via `load_sess`
    name=None, # Dialog name; the session id if None
    mx=2000, # Maximum characters per rendered tool input/output string; None disables truncation (see `hist2fmt`)
    recs=None, # Already-loaded records; if given, `sid` and `cwd` are ignored
):
    "The conversation of a session as a dialog, one prompt per user turn; `system` records ride along as tagged raws"
    if recs is None:
        sid = sid or cur_sess(cwd)
        recs = load_sess(sid,cwd)
    recs = strip_think(sess_thread(L(recs)))
    dlg = chat2dlg(recs2chat(recs), name or sid or 'session', mx=mx)
    prompts,t,anchor = [m for m in dlg.messages if m.msg_type==sprompt],-1,None
    for r in recs:
        r = obj2dict(r)
        if r['type']=='user' and rec_role(r)!='tool':
            t += 1
            anchor = prompts[t]
            anchor.meta['timestamp'] = r.get('timestamp')
        elif r['type']=='assistant':
            if u := nested_idx(r,'message','usage'): prompts[t].meta['usage'] = u
        elif r['type']=='system':
            kw = dict(after=anchor) if anchor else dict(idx=0)
            anchor = dlg.mk_message('', msg_type=sraw, meta=dict(rec_kind='system',rec=r), **kw)
    return dlg

# %% ../nbs/03_ant.ipynb #3991610a
def resolve_session(ref=None, cwd='.'):
    "Resolve a session id or custom title to `(sid,path)`"
    cwd = Path(cwd).expanduser()
    ref = ref or cur_sess(cwd)
    path = sess_file(ref, cwd)
    if path.exists(): return ref,path
    path = sess_by_name(ref, cwd)
    if path: return path.stem,path
    raise FileNotFoundError(f'No session named or identified by {ref!r} in {cwd}')

# %% ../nbs/03_ant.ipynb #558f940f
def _is_synthetic_compact(r):
    "Check whether `r` is an llmsurgery compact summary"
    return bool(r.get('isCompactSummary') and r.get('llmsurgeryCompact'))

def _is_compact_wrapper(r):
    "Check whether `r` belongs to the synthetic `/compact` display"
    return bool(r.get('llmsurgeryCompact'))

# %% ../nbs/03_ant.ipynb #d00d96be
def split_compaction(recs):
    "Return the prior compact body and records added after it"
    thread = sess_thread(recs)
    idxs = [i for i,r in enumerate(thread) if _is_synthetic_compact(r)]
    if not idxs: return '',thread
    i,j = idxs[-1],idxs[-1]+1
    while j<len(thread) and _is_compact_wrapper(thread[j]): j += 1
    return compact_body(rec_txt(thread[i])),thread[j:]

# %% ../nbs/03_ant.ipynb #349542e6
def sess_meta(recs):
    "Latest available session metadata for synthetic records"
    ks = 'session_id userType entrypoint cwd sessionId version gitBranch slug'.split()
    vals = {k:next((r[k] for r in reversed(recs) if r.get(k) is not None), None) for k in ks}
    return {k:v for k,v in vals.items() if v is not None}

# %% ../nbs/03_ant.ipynb #87077273
def compact_records(recs, content, pre_toks, post_toks):
    "Create a tagged compact boundary, summary, and visible `/compact` records"
    meta,tag = sess_meta(recs),dict(llmsurgeryCompact=True, llmsurgeryCompactVersion=1)
    prior = max((o.get('compactMetadata', {}).get('cumulativeDroppedTokens', 0) for o in recs), default=0)
    boundary = mk_rec('system', '', cwd=meta['cwd'])
    boundary.pop('message')
    boundary.update(meta)
    boundary.update(tag)
    boundary.update(subtype='compact_boundary', content='', level='info', isMeta=False,
        compactMetadata=dict(preTokens=pre_toks, postTokens=post_toks, cumulativeDroppedTokens=prior+max(0, pre_toks-post_toks)))
    summary = mk_rec('user', content, cwd=meta['cwd'], ts=boundary['timestamp'],
        promptId=stable_uuid(f"{boundary['uuid']}:prompt"), isVisibleInTranscriptOnly=True, isCompactSummary=True)
    summary.update(meta)
    summary.update(tag)
    summary['parentUuid'] = boundary['uuid']
    caveat = mk_rec('user', '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>', cwd=meta['cwd'])
    command = mk_rec('user', '<command-name>/compact</command-name>\n            <command-message>compact</command-message>\n            <command-args></command-args>', cwd=meta['cwd'])
    stdout = mk_rec('user', '<local-command-stdout>Compacted (ctrl+o to see full summary)</local-command-stdout>', cwd=meta['cwd'])
    for prev,o in zip((summary,caveat,command), (caveat,command,stdout)): o['parentUuid'] = prev['uuid']
    for o in (caveat,command,stdout): o.update(meta); o.update(tag)
    return L(boundary,summary,caveat,command,stdout)

# %% ../nbs/03_ant.ipynb #d8ce7eef
def prepare_compaction(ref, cwd='.', policy=compact_policy, enc=None):
    "Prepare an incremental synthetic compaction without writing it"
    cwd = Path(cwd).expanduser()
    sid,path = resolve_session(ref, cwd)
    recs = load_sess(sid, cwd)
    prior,new_recs = split_compaction(recs)
    msgs = recs2chat(strip_think(new_recs))
    if not msgs: raise ValueError(f'No new messages to compact in {sid}')
    new_chat = compact_chat(msgs, enc=enc, last_n=5, **policy)
    new_full = compact_chat(msgs, enc=enc, **{k:10**9 for k in policy})
    chat,full = join_compacts(prior,new_chat),join_compacts(prior,new_full)
    content = compact_content(chat, path)
    pre_toks,post_toks = len_toks(full, enc),len_toks(content, enc)
    name = next((r.customTitle for r in reversed(recs) if r.type=='custom-title'), None)
    return AttrDict(sid=sid,name=name,cwd=cwd,path=path,records=compact_records(recs,content,pre_toks,post_toks),
        prior=prior,new_chat=new_chat,chat=chat,full=full,content=content,pre_toks=pre_toks,post_toks=post_toks)

# %% ../nbs/03_ant.ipynb #20acff2d
def append_compaction(compaction):
    "Append a prepared compaction and restore its session name"
    with Path(compaction.path).open('a') as f: f.writelines(xdumps(o)+'\n' for o in compaction.records)
    if compaction.name: name_sess(compaction.sid, compaction.name, compaction.cwd)
    return compaction.path

# %% ../nbs/03_ant.ipynb #448de8f6
def compact_session(ref, cwd='.', policy=compact_policy, enc=None):
    "Generate and append a synthetic session compaction"
    compaction = prepare_compaction(ref, cwd, policy, enc)
    append_compaction(compaction)
    return compaction
