"""Docs: https://AnswerDotAI.github.io/llmsurgery/compact.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_compact.ipynb.

# %% auto #0
__all__ = ['compact_policy', 'tool_part', 'tool_result', 'compact_enc', 'enc_toks', 'len_toks', 'trunctoks_mid', 'compact_text',
           'compact_result', 'fenced_code', 'bash_call', 'generic_call', 'compact_call', 'compact_user_part',
           'compact_user', 'compact_asst_part', 'compact_asst', 'compact_tool', 'compact_msg', 'compact_chat',
           'compact_content', 'compact_body', 'join_compacts']

# %% ../nbs/05_compact.ipynb #de23b4fe
from fastcore.utils import *
from functools import cache
from fastllm.chat import mk_msg, mk_msgs
from fastllm.types import PartType,Part,Msg

import re,tiktoken

# %% ../nbs/05_compact.ipynb #2fe68d07
def tool_part(tool_name, **arguments):
    "Create a canonical tool-use part"
    return Part(PartType.tool_use, data={'name':tool_name, 'arguments':arguments})

def tool_result(text):
    "Create a canonical tool-result message"
    return Msg('tool', [Part(PartType.tool_result, text=text)])

# %% ../nbs/05_compact.ipynb #7ad24f5a
_compact_enc_name = 'o200k_base'

@cache
def compact_enc(): return tiktoken.get_encoding(_compact_enc_name)

def enc_toks(s, enc=None):
    "Encode `s` into tokens."
    if enc is None: enc = compact_enc()
    return enc.encode(s, disallowed_special=())

def len_toks(s, enc=None):
    "Number of tokens in `s`."
    return len(enc_toks(s, enc))

# %% ../nbs/05_compact.ipynb #396a6a3b
def trunctoks_mid(s, max_toks, enc=None, mark=' … '):
    """Truncate the middle of `s` to at most `max_toks` tokens."""
    if enc is None: enc = compact_enc()
    if max_toks <= 0: return ''
    toks = enc_toks(s, enc)
    if len(toks) <= max_toks: return s
    mtoks = enc_toks(mark, enc)[:max_toks]
    n = max_toks - len(mtoks)
    a, b = (n + 1) // 2, n // 2
    tail = toks[-b:] if b else []
    return enc.decode(toks[:a] + mtoks + tail)

# %% ../nbs/05_compact.ipynb #f55fe38a
def compact_text(s, mark, max_toks, enc=None):
    """Render delimited prose within `max_toks`."""
    return trunctoks_mid(f'{mark} {s.strip()} {mark}', max_toks, enc)

# %% ../nbs/05_compact.ipynb #e3f22ddb
def compact_result(s, max_toks, enc=None):
    "Render a tool result within `max_toks`."
    text = ' ¶ '.join(line.strip() for line in s.splitlines() if line.strip())
    return trunctoks_mid(f'> {text}' if text else '>', max_toks, enc)

# %% ../nbs/05_compact.ipynb #783d1ab0
def fenced_code(code, max_toks, enc=None):
    "Render Python in a safe Markdown fence within `max_toks`."
    code = code.strip()
    runs = re.findall(r'^ {0,3}(`{3,})[ \t]*$', code, flags=re.MULTILINE)
    fence = '`' * max(3, max(map(len, runs), default=0) + 1)
    pre,suf = f'{fence}python\n',f'\n{fence}'
    full = pre + code + suf
    if len_toks(full, enc) <= max_toks: return full
    if len_toks(pre + suf, enc) > max_toks:
        raise ValueError('Token budget is too small for a fenced block')
    body_toks = min(len_toks(code, enc), max_toks)
    while body_toks:
        body = trunctoks_mid(code, body_toks, enc)
        result = pre + body + suf
        if len_toks(result, enc) <= max_toks: return result
        body_toks -= 1
    return pre + suf

# %% ../nbs/05_compact.ipynb #99ed7e9d
def bash_call(command, max_toks, enc=None):
    "Render a Bash command within `max_toks`."
    text = '! ' + ' ¶ '.join(line.strip() for line in command.splitlines() if line.strip())
    return trunctoks_mid(text, max_toks, enc)

# %% ../nbs/05_compact.ipynb #a76c5354
def generic_call(name, args, max_toks, enc=None):
    "Render a generic tool call within `max_toks`."
    vals = ', '.join(f"{k}={v!r}".replace('\\n', ' ¶ ') for k,v in args.items())
    return trunctoks_mid(f'▶ {name}({vals})', max_toks, enc)

# %% ../nbs/05_compact.ipynb #cef7d16f
def compact_call(p, max_toks, enc=None):
    "Render a tool-use part within `max_toks`."
    name, args = p.data['name'], p.data['arguments']
    if name == 'mcp__clikernel__execute': return fenced_code(args['code'], max_toks, enc)
    if name == 'Bash': return bash_call(args.get('command', ''), max_toks, enc)
    return generic_call(name, args, max_toks, enc)

# %% ../nbs/05_compact.ipynb #d5c7af9a
def compact_user_part(p, max_toks, enc=None):
    "Render one user-text part, replacing injected skill contents."
    text = '…skill text compacted: re-invoke before relying on it…' if p.text.startswith('Base directory for this skill:') else p.text
    return compact_text(text, '§', max_toks, enc)

def compact_user(m, max_toks, enc=None):
    "Render the text parts of a user message."
    return '\n'.join(compact_user_part(p, max_toks, enc)
        for p in m.content if p.type == PartType.text)

# %% ../nbs/05_compact.ipynb #c43c4e7e
def compact_asst_part(p, text_toks, call_toks, enc=None):
    "Render one assistant part."
    if p.type == PartType.text: return compact_text(p.text, '»', text_toks, enc)
    if p.type == PartType.tool_use: return compact_call(p, call_toks, enc)

def compact_asst(m, text_toks, call_toks, enc=None):
    "Render an assistant message."
    parts = (compact_asst_part(p, text_toks, call_toks, enc) for p in m.content)
    return '\n'.join(filter(None, parts))

# %% ../nbs/05_compact.ipynb #30805c31
def compact_tool(m, max_toks, enc=None):
    "Render the result parts of a tool message."
    return '\n'.join(compact_result(p.text, max_toks, enc)
        for p in m.content if p.type == PartType.tool_result)

def compact_msg(m, user_toks, asst_toks, call_toks, result_toks, enc=None):
    "Render one canonical message."
    if m.role == 'user': return compact_user(m, user_toks, enc)
    if m.role == 'assistant': return compact_asst(m, asst_toks, call_toks, enc)
    if m.role == 'tool': return compact_tool(m, result_toks, enc)

# %% ../nbs/05_compact.ipynb #44c88dee
def compact_chat(msgs, user_toks, asst_toks, call_toks, result_toks, enc=None, last_n=0):
    "Render canonical messages as compact user-led turns."
    policy = dict(user_toks=user_toks, asst_toks=asst_toks,
        call_toks=call_toks, result_toks=result_toks)
    full_policy = {k:10**9 for k in policy}
    turns,nfull = [],len(msgs)-last_n
    for i,m in enumerate(msgs):
        if m.role == 'user' or not turns: turns.append([])
        p = full_policy if i >= nfull else policy
        turns[-1].append(compact_msg(m, enc=enc, **p))
    rendered = ('\n'.join(filter(None, turn)) for turn in turns)
    return '\n\n***\n\n'.join(filter(None, rendered))

# %% ../nbs/05_compact.ipynb #42df86f5
compact_policy = dict(user_toks=1000, asst_toks=100, call_toks=50, result_toks=25)

# %% ../nbs/05_compact.ipynb #5005ee37
_re_skill = re.compile(r"▶ Skill\(skill='([^']+)'")

def compact_content(chat, path, notes=''):
    "Wrap compact conversation text as a continuation document."
    intro = "This session is being continued from an earlier conversation. `§ … §` encloses user text; `» … »` encloses assistant text; fenced `python` is persistent-kernel execution; `!` marks Bash; `▶` marks another tool call; `>` marks its result; `¶` replaces a newline; `***` separates user-led turns; and ` … ` marks removed middle content. The final five messages are preserved untruncated. This representation is for orientation only: never copy code or commands from it; reopen the original transcript or source file first."
    res = f'{intro}\n\n## Conversation\n\n{chat}'
    if notes: res += f'\n\n## Auto-generated continuation notes\n\n{notes}'
    res += f'\n\nIf further detail is needed, read the complete transcript at: {path}'
    if skills := L(_re_skill.findall(chat)).unique():
        res += '\n\nSkill contents were compacted out above. Before relying on any skill guidance, re-invoke it: ' + ', '.join(f'Skill({s})' for s in skills) + '.'
    return res

# %% ../nbs/05_compact.ipynb #01c63a09
def compact_body(content):
    "Extract the conversation body from a compaction document."
    body = content.split('\n\n## Conversation\n\n', 1)[1]
    body = body.split('\n\n## Auto-generated continuation notes\n\n', 1)[0]
    return body.rsplit('\n\nIf further detail is needed, read the complete transcript at:', 1)[0]

# %% ../nbs/05_compact.ipynb #5fac4786
def join_compacts(*parts):
    "Join non-empty compact conversation segments."
    return '\n\n***\n\n'.join(part for part in parts if part)
