"""Fill in a module description here

Docs: https://AnswerDotAI.github.io/llmsurgery/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #e03deade
def foo(): pass
