"""Messages, dialogs, and attachments: the data model for LLM conversations stored as notebooks

Docs: https://AnswerDotAI.github.io/llmsurgery/dialog.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_dialog.ipynb.

# %% auto #0
__all__ = ['smsg_types', 'scode', 'snote', 'sprompt', 'sraw', 'tiny_png', 'add_id_hash', 'Dialog', 'mk_output', 'mk_displayobj',
           'displayobj', 'mk_code_output', 'code_output', 'prompt_output', 'Message', 'get_msg', 'get_output_mds',
           'ruuid4', 'Attachment']

# %% ../nbs/00_dialog.ipynb #5571d07a
import base64, copy, random, weakref
from json import loads
from fastcore.utils import *

# %% ../nbs/00_dialog.ipynb #9d79a4b9
smsg_types = scode,snote,sprompt,sraw = "code","note","prompt","raw"

# %% ../nbs/00_dialog.ipynb #61883528
def add_id_hash(cls, attr):
    'Adds `__eq__` and `__hash__` to a cls based on a str or int `attr` id'
    @patch
    def __eq__(self:cls, a):
        if a is None: return False
        if isinstance(a, cls): return getattr(self, attr)==getattr(a, attr)
        if isinstance(a, (str, int)): return getattr(self, attr)==a
        return False
    @patch
    def __hash__(self:cls): return hash(getattr(self, attr))

# %% ../nbs/00_dialog.ipynb #bc320318
class Dialog(BasicRepr):
    "A named, ordered list of messages"
    def __init__(self,
        name, # Dialog name, usually the file stem
        messages=None, # Initial `Message`s
        meta=None, # Notebook-level metadata dict, carried verbatim through save/load
    ):
        self.name,self.messages,self.meta = str(name),listify(messages),dict(meta or {})

    def _repr_markdown_(self):
        msgs = ''
        if self.messages:
            msgr = '\n'.join(f'- {o.summ}' for o in self.messages)
            msgs = f'''
<details markdown='1'>

{msgr}

</details>'''
        return f'''
**{self.name}**

{msgs}'''

add_id_hash(Dialog, 'name')

# %% ../nbs/00_dialog.ipynb #579ba71b
def mk_output(typ, d, meta=None, **kw): return dict(output_type=typ, metadata=meta or {}, data=d, **kw)
def mk_displayobj(d, meta=None): return mk_output('display_data', d, meta)
def displayobj(data='', subtype='plain', mimetype='text', meta=None): return mk_displayobj({f'{mimetype}/{subtype}': data}, meta)
def mk_code_output(d): return [mk_output('execute_result', d, execution_count=1)]
def code_output(result='', subtype='plain', mimetype='text'): return mk_code_output({f'{mimetype}/{subtype}': result})

def prompt_output(txt=''):
    "Create prompt output list from AI response text"
    return [displayobj(txt, 'markdown', meta={'is_ai_res': True})] if txt else []

# %% ../nbs/00_dialog.ipynb #b25cd968
class Message:
    meta_attrs = {} # Attribute name -> cell metadata key: fields a subclass promotes from cell metadata and serializes back

    def __init__(self,
        content='', # The message text: markdown, code, or a prompt's request
        dlg=None, # The `Dialog` this message belongs to
        output='', # Jupyter-style output list (code and prompt messages), or ''
        id=None, # Message id; `_` plus 4 random hex bytes if None
        msg_type='code', # One of `smsg_types`: code, note, prompt, or raw
        attachments=None, # `Attachment`s carried by the message
        meta=None, # Remaining cell metadata, carried verbatim through save/load
        **xtras, # Extra attributes to store as-is
    ):
        # Prepend `_` to ensure it is a valid DOM id too
        if id is None: id = '_'+rtoken_hex(4)
        attachments = listify(attachments)
        meta = dict(meta or {})
        if content  is UNSET: content = ''
        if msg_type is UNSET: msg_type = snote
        if output   is UNSET: output=[] if msg_type in (scode, sprompt) else ''
        elif msg_type==sprompt and isinstance(output, str): output = prompt_output(output)
        self.msg_type = msg_type # Set type first, since it clears output
        self._dlg = weakref.ref(dlg) if dlg else None # weakref to avoid circular ref
        store_attr(but=['dlg', 'msg_type', 'xtras'])
        for k,v in xtras.items(): setattr(self, k, v)

    # Invalidation hooks, called when output/content/type change; subclasses clear their extra caches here
    def clear_out_cache(self): self._ai_rend = None
    def clear_inp_cache(self): pass

    @DepProp
    def output(self): self.clear_out_cache()

    @output.norm
    def output(self, v): return [] if v is None and self.msg_type in (scode, sprompt) else v

    @DepProp
    def content(self): self.clear_inp_cache()

    @DepProp
    def msg_type(self):
        self.clear_out_cache()
        self.clear_inp_cache()
        self.output = [] if self.msg_type in (scode, sprompt) else ''

    @property
    def ai_res(self):
        "Extract AI response text from prompt output list"
        if self.msg_type != sprompt: return ''
        if isinstance(self.output, str): return self.output  # Handle legacy/direct string
        if res := first(L(self.output).filter(lambda x: nested_idx(x, 'metadata', 'is_ai_res'))):
            return nested_idx(res, 'data', 'text/markdown') or ''
        return ''

    def __deepcopy__(self, memo):
        cls = self.__class__
        result = cls.__new__(cls)
        memo[id(self)] = result
        for k, v in self.__dict__.items():
            if k.startswith(('_msgidle','_dlg')): setattr(result, k, v)
            else: setattr(result, k, copy.deepcopy(v, memo))
        return result

    @property
    def dlg(self): return self._dlg() if self._dlg else None
    @dlg.setter
    def dlg(self, v): self._dlg = weakref.ref(v)
    @property
    def __flds__(self): return vars_pub(self) + ['content', 'output', 'msg_type']
    @property
    def flds(self): return [o for o in self.__flds__ if o not in ('content', 'output', 'attachments')]
    @property
    def summ(self): return self.content + (f" ⇒ {self.output}" if self.output else '')
    __repr__ = basic_repr('id,content,output,msg_type')

add_id_hash(Message, 'id')
Dialog.msg_cls = Message

# %% ../nbs/00_dialog.ipynb #e3e3ab18
@patch
def _repr_markdown_(self:Message):
    detls = '\n'.join(f'- {k}: {getattr(self, k)}' for k in self.flds)
    return f"""{self.summ}

<details>

{detls}

</details>"""

# %% ../nbs/00_dialog.ipynb #e4fb159d
@patch
def update(self:Message, **kwargs):
    "Update message attributes with provided keyword arguments"
    for k, v in kwargs.items():
        if v is not UNSET: setattr(self, k, v)
    return self

# %% ../nbs/00_dialog.ipynb #a0465cdb
@patch
def mk_message(self:Dialog,
    content:str, # Message text
    idx=-1, # Insert position; -1 appends
    after=None, # Insert after this `Message` or id
    before=None, # Insert before this `Message` or id
    msg_type=scode, # One of `smsg_types`
    output='', # Output list; code messages also accept a JSON string
    **kwargs, # Passed to `msg_cls`
):
    "Make new message and insert it into notebook before/after specified cell, or start of list (idx=0) by default"
    if msg_type==scode and isinstance(output,str): output = loads(output or '[]')
    msg = self.msg_cls(content, self, msg_type=msg_type, output=output, **kwargs)
    if isinstance(after,  Message): after =after.id
    if isinstance(before, Message): before=before.id
    if after is not None: idx = next((i for i,c in enumerate(self.messages) if c.id==after ), -1)+1
    elif before is not None: idx = next((i for i,c in enumerate(self.messages) if c.id==before), -1)
    if idx==-1: idx=len(self.messages)
    self.messages.insert(idx, msg)
    return msg

# %% ../nbs/00_dialog.ipynb #d499654b
@patch
def mk_messages(self:Dialog, msgs, after=None, before=None):
    "Make new messages and insert them sequentially into the notebook after/before a specific message."
    def _kws(m): return {o: getattr(m,o) for o in m.flds if o!='id'}
    return [after:=self.mk_message(m.content,output=m.output,attachments=m.attachments,after=after, before=before, **_kws(m)) for m in msgs]

# %% ../nbs/00_dialog.ipynb #e668fd4f
@patch
def insert_after(self:Message, msgs):
    curr = self.dlg.messages
    idx = curr.index(self)
    curr[idx+1:idx+1] = msgs
    for m in msgs: m.dlg = self.dlg

# %% ../nbs/00_dialog.ipynb #0c98e2c1
@patch
def _neighbor(self:Message, fwd=True, pred=None):
    "Find next (fwd=True) or previous (fwd=False) message, optionally filtered by pred."
    msgs = self.dlg.messages
    idx = msgs.index(self)
    slc = msgs[idx+1:] if fwd else reversed(msgs[:idx])
    return first(m for m in slc if not pred or pred(m))

@patch
def next(self:Message): return self._neighbor()
@patch
def previous(self:Message): return self._neighbor(fwd=False)
@patch
def rel_msg(self:Message, is_up:bool): return self._neighbor(fwd=not is_up)

# %% ../nbs/00_dialog.ipynb #991f63bc
@patch
def find_msg(self:Dialog, content): return first(m for m in self.messages if m.content==content)

def get_msg(id_, dlg):
    if not dlg or not id_: return
    return first(o for o in dlg.messages if o.id==id_)

# %% ../nbs/00_dialog.ipynb #2b6197c3
@patch
def remove_msgs(self:Dialog, msgs):
    "Remove messages from dialog, return removed list"
    s = set(msgs)
    self.messages[:] = [m for m in self.messages if m not in s]
    return msgs

@patch
def remove_from_dlg(self:Message):
    "Remove this message from its dialog"
    return self.dlg.remove_msgs([self])

# %% ../nbs/00_dialog.ipynb #e074c630
@patch(as_prop=True)
def has_error(self:Message):
    if self.msg_type != scode: return False
    return any(o.get('output_type') == 'error' for o in (self.output or []))

def get_output_mds(output):
    "Extract text/markdown content from code outputs (display_data and execute_result)"
    if not output: return []
    return [o['data']['text/markdown'] for o in output
        if o.get('output_type') in ('display_data', 'execute_result')
        and 'text/markdown' in o.get('data', {})]

# %% ../nbs/00_dialog.ipynb #1c03c386
def ruuid4():
    "Generate a deterministic UUID4-like string using rtoken_hex"
    parts = [rtoken_hex(4), rtoken_hex(2), rtoken_hex(2), rtoken_hex(2), rtoken_hex(6)]
    parts[2], parts[3] = '4' + parts[2][1:], format(random.randint(8, 11), 'x') + parts[3][1:]
    return f"{parts[0]}-{parts[1]}-{parts[2]}-{parts[3]}-{parts[4]}"

class Attachment(BasicRepr):
    def __init__(self, data:bytes, content_type:str, id:str=''):
        if not id: id=ruuid4()
        store_attr()

add_id_hash(Attachment, 'id')

@patch
def mk_attachment(self:Message, data:bytes, content_type:str, id:str=''):
    att = Attachment(data=data, content_type=content_type, id=id)
    return self.attachments.append(att)

# %% ../nbs/00_dialog.ipynb #18689653
tiny_png = base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==')

# %% ../nbs/00_dialog.ipynb #036da886
@patch
def todict(self:Dialog): return {k:v for k,v in asdict(self).items() if k[0]!='_'}
