"""Messages, dialogs, and attachments: the data model for LLM conversations stored as notebooks

Docs: https://AnswerDotAI.github.io/llmsurgery/dialog.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_dialog.ipynb.

# %% auto #0
__all__ = ['smsg_types', 'scode', 'snote', 'sprompt', 'sraw', 'tiny_png', 'add_id_hash', 'Msgs', 'Dialog', 'mk_output',
           'mk_displayobj', 'displayobj', 'mk_code_output', 'code_output', 'prompt_output', 'Message', 'MsgRow',
           'MsgRows', 'get_msg', 'header_info', 'section_msgs', 'get_output_mds', 'mk_jmsg', 'mk_stream', 'mk_error',
           'mk_dispdata', 'mk_execresult', 'output_from_msg', 'dlg2py', 'copy_export', 'merge_metas', 'merge_parts',
           'ruuid4', 'Attachment']

# %% ../nbs/00_dialog.ipynb #5571d07a
import base64, copy, random, weakref
from json import loads, dumps
from fastcore.utils import *
from fastcore.nbio import mk_cell

# %% ../nbs/00_dialog.ipynb #9d79a4b9
smsg_types = scode,snote,sprompt,sraw = "code","note","prompt","raw"

# %% ../nbs/00_dialog.ipynb #61883528
def add_id_hash(cls, attr):
    'Adds `__eq__` and `__hash__` to a cls based on a str or int `attr` id'
    @patch
    def __eq__(self:cls, a):
        if a is None: return False
        if isinstance(a, cls): return getattr(self, attr)==getattr(a, attr)
        if isinstance(a, (str, int)): return getattr(self, attr)==a
        return False
    @patch
    def __hash__(self:cls): return hash(getattr(self, attr))

# %% ../nbs/00_dialog.ipynb #352b878b
class Msgs(L):
    "A list of `Message`s with a preview-per-line repr"
    def show(self,
        maxlen:int=120, # Maximum characters per preview line
        rows:int=None, # Max messages to show (None: all)
    ):
        "One `preview` line per message"
        xs = self if rows is None else self[:rows]
        res = '\n'.join(m.preview(maxlen) for m in xs)
        if rows is not None and len(self)>rows: res += f'\n…({len(self)-rows} more)'
        return PrettyString(res)

    def __repr__(self): return str(self.show(rows=20))

# %% ../nbs/00_dialog.ipynb #bc320318
class Dialog(BasicRepr):
    "A named, ordered list of messages"
    def __init__(self,
        messages=None, # Initial `Message`s, shared not copied: a wrap of live messages is a view over the originals
        name='', # Dialog name, usually the file stem
        meta=None, # Notebook-level metadata dict, carried verbatim through save/load
    ):
        if isinstance(messages, str): raise TypeError("Dialog(messages, name): first arg is the messages - pass name='...' by keyword")
        self.name,self.messages,self.meta = str(name),Msgs(listify(messages)),dict(meta or {})
        for m in self.messages:  # claim only orphans: wrapping live messages must not steal them from their real dialog
            if m.dlg is None: m.dlg = self

    def _repr_markdown_(self):
        msgs = ''
        if self.messages:
            msgr = '\n'.join(f'- {o.summ}' for o in self.messages)
            msgs = f'''
<details markdown='1'>

{msgr}

</details>'''
        return f'''
**{self.name}**

{msgs}'''

add_id_hash(Dialog, 'name')

# %% ../nbs/00_dialog.ipynb #579ba71b
def mk_output(typ, d, meta=None, **kw): return dict(output_type=typ, metadata=meta or {}, data=d, **kw)
def mk_displayobj(d, meta=None): return mk_output('display_data', d, meta)
def displayobj(data='', subtype='plain', mimetype='text', meta=None): return mk_displayobj({f'{mimetype}/{subtype}': data}, meta)
def mk_code_output(d): return [mk_output('execute_result', d, execution_count=1)]
def code_output(result='', subtype='plain', mimetype='text'): return mk_code_output({f'{mimetype}/{subtype}': result})

def prompt_output(txt=''):
    "Create prompt output list from AI response text"
    return [displayobj(txt, 'markdown', meta={'is_ai_res': True})] if txt else []

# %% ../nbs/00_dialog.ipynb #b25cd968
class Message:
    meta_attrs = {} # Attribute name -> cell metadata key: fields a subclass promotes from cell metadata and serializes back

    def __init__(self,
        content='', # The message text: markdown, code, or a prompt's request
        dlg=None, # The `Dialog` this message belongs to
        output='', # Jupyter-style output list (code and prompt messages), or ''
        id=None, # Message id; 4 random hex bytes if None
        msg_type='code', # One of `smsg_types`: code, note, prompt, or raw
        attachments=None, # `Attachment`s carried by the message
        meta=None, # Remaining cell metadata, carried verbatim through save/load
        **xtras, # Extra attributes to store as-is
    ):
        "An ipynb cell, or Solveit message (which adds the `prompt` type)"
        # Bare hex, coerced to str: hosts add any display prefix (e.g. solveit's DOM `_`) at their boundary
        id = rtoken_hex(4) if id is None else str(id)
        attachments = listify(attachments)
        meta = dict(meta or {})
        if content  is UNSET: content = ''
        if msg_type is UNSET: msg_type = snote
        if output   is UNSET: output=[] if msg_type in (scode, sprompt) else ''
        self.msg_type = msg_type # Set type first, since it clears output
        self._dlg = weakref.ref(dlg) if dlg else None # weakref to avoid circular ref
        store_attr(but=['dlg', 'msg_type', 'xtras'])
        for k,v in xtras.items(): setattr(self, k, v)

    # Invalidation hooks, called when output/content/type change; subclasses clear their extra caches here
    def clear_out_cache(self): self._ai_rend = None
    def clear_inp_cache(self): pass

    @DepProp
    def output(self): self.clear_out_cache()

    @output.norm
    def output(self, v):
        if self.msg_type==sprompt and isinstance(v, str): return prompt_output(v)
        return [] if v is None and self.msg_type in (scode, sprompt) else v

    @DepProp
    def content(self): self.clear_inp_cache()

    @DepProp
    def msg_type(self):
        self.clear_out_cache()
        self.clear_inp_cache()
        self.output = [] if self.msg_type in (scode, sprompt) else ''

    @property
    def ai_res(self):
        "Extract AI response text from prompt output list"
        if self.msg_type != sprompt: return ''
        if isinstance(self.output, str): return self.output  # Handle legacy/direct string
        if res := first(L(self.output).filter(lambda x: nested_idx(x, 'metadata', 'is_ai_res'))):
            return nested_idx(res, 'data', 'text/markdown') or ''
        return ''

    def __deepcopy__(self, memo):
        cls = self.__class__
        result = cls.__new__(cls)
        memo[id(self)] = result
        for k, v in self.__dict__.items():
            if k.startswith(('_msgidle','_dlg')): setattr(result, k, v)
            else: setattr(result, k, copy.deepcopy(v, memo))
        return result

    @property
    def dlg(self): return self._dlg() if self._dlg else None
    @dlg.setter
    def dlg(self, v): self._dlg = weakref.ref(v)
    @property
    def __flds__(self): return vars_pub(self) + ['content', 'output', 'msg_type']
    @property
    def flds(self): return [o for o in self.__flds__ if o not in ('content', 'output', 'attachments')]
    @property
    def summ(self): return truncstr(self.content, 96) + (f" ⇒ {truncstr(str(self.output), 60)}" if self.output else '')
    __repr__ = basic_repr('id,content,output,msg_type')

# %% ../nbs/00_dialog.ipynb #135858d9
add_id_hash(Message, 'id')
Dialog.msg_cls = Message

# %% ../nbs/00_dialog.ipynb #e3e3ab18
@patch
def _repr_markdown_(self:Message):
    detls = '\n'.join(f'- {k}: {getattr(self, k)}' for k in self.flds)
    return f"""{self.summ}

<details>

{detls}

</details>"""

# %% ../nbs/00_dialog.ipynb #145c8a42
@patch
def preview(self:Message,
    maxlen:int=120, # Maximum characters in the line
):
    "Escaped one-line summary, the row format for `Msgs` displays: `id:t:content` (t: c=code n=note p=prompt r=raw)"
    s = f"{self.id}:{self.msg_type[0]}:{self.content}"
    if self.msg_type==sprompt and self.ai_res: s += f" ⇒ reply({len(self.ai_res)})"
    elif self.output: s += f" ⇒ out({len(str(self.output))})"
    return truncstr(s.replace('\n', '\\n'), maxlen)

# %% ../nbs/00_dialog.ipynb #a72644ce
class MsgRow:
    "Snapshot of one message: `id`, `msg_type`, `content`, `out` (reply or output text), and `meta`; shown as its preview line"
    def __init__(self, m, maxlen=120):
        self.id,self.msg_type,self.content = m.id,m.msg_type,m.content
        self.meta = copy.deepcopy(m.meta)
        self.out = (m.ai_res or '') if m.msg_type==sprompt else str(m.output or '')
        self._pv = m.preview(maxlen)
    def __repr__(self): return self._pv

class MsgRows(list):
    "A list of `MsgRow`s, one preview line each"
    def __repr__(self): return '\n'.join(repr(o) for o in self)

# %% ../nbs/00_dialog.ipynb #e4fb159d
@patch
def update(self:Message, **kwargs):
    "Update message attributes with provided keyword arguments"
    for k, v in kwargs.items():
        if v is not UNSET: setattr(self, k, v)
    return self

# %% ../nbs/00_dialog.ipynb #a0465cdb
@patch
def mk_message(self:Dialog,
    content:str, # Message text
    idx=-1, # Insert position; -1 appends
    after=None, # Insert after this `Message` or id
    before=None, # Insert before this `Message` or id
    msg_type=scode, # One of `smsg_types`
    output='', # Output list; code messages also accept a JSON string
    **kwargs, # Passed to `msg_cls`
):
    "Make new message and insert it into notebook before/after specified cell, or start of list (idx=0) by default"
    if msg_type==scode and isinstance(output,str): output = loads(output or '[]')
    msg = self.msg_cls(content, self, msg_type=msg_type, output=output, **kwargs)
    if 'id' not in kwargs:  # generated ids must not collide, even if the global random stream was re-seeded
        while any(m.id==msg.id for m in self.messages): msg.id = rtoken_hex(4)
    if isinstance(after,  Message): after =after.id
    if isinstance(before, Message): before=before.id
    if after is not None: idx = next((i for i,c in enumerate(self.messages) if c.id==after ), -1)+1
    elif before is not None: idx = next((i for i,c in enumerate(self.messages) if c.id==before), -1)
    if idx==-1: idx=len(self.messages)
    self.messages.insert(idx, msg)
    return msg

# %% ../nbs/00_dialog.ipynb #d499654b
@patch
def mk_messages(self:Dialog, msgs, after=None, before=None):
    "Make new messages and insert them sequentially into the notebook after/before a specific message."
    def _kws(m): return {o: getattr(m,o) for o in m.flds if o!='id'}
    return [after:=self.mk_message(m.content,output=m.output,attachments=m.attachments,after=after, before=before, **_kws(m)) for m in msgs]

# %% ../nbs/00_dialog.ipynb #e668fd4f
@patch
def insert_after(self:Message, msgs):
    curr = self.dlg.messages
    idx = curr.index(self)
    curr[idx+1:idx+1] = msgs
    for m in msgs: m.dlg = self.dlg

# %% ../nbs/00_dialog.ipynb #0c98e2c1
@patch
def _neighbor(self:Message, fwd=True, pred=None):
    "Find next (fwd=True) or previous (fwd=False) message, optionally filtered by pred."
    msgs = self.dlg.messages
    idx = msgs.index(self)
    slc = msgs[idx+1:] if fwd else reversed(msgs[:idx])
    return first(m for m in slc if not pred or pred(m))

@patch
def next(self:Message): return self._neighbor()
@patch
def previous(self:Message): return self._neighbor(fwd=False)
@patch
def rel_msg(self:Message, is_up:bool): return self._neighbor(fwd=not is_up)

# %% ../nbs/00_dialog.ipynb #991f63bc
@patch
def find_msg(self:Dialog, content): return first(m for m in self.messages if m.content==content)

def get_msg(id_, dlg):
    if not dlg or not id_: return
    return first(o for o in dlg.messages if o.id==id_)

# %% ../nbs/00_dialog.ipynb #2b6197c3
@patch
def remove_msgs(self:Dialog, msgs):
    "Remove messages from dialog, return removed list"
    s = set(msgs)
    self.messages[:] = [m for m in self.messages if m not in s]
    return msgs

@patch
def remove_from_dlg(self:Message):
    "Remove this message from its dialog"
    return self.dlg.remove_msgs([self])

# %% ../nbs/00_dialog.ipynb #03ed3d82
_re_hdr = re.compile(r' {0,3}(?P<level>#{1,6})\s+(?P<text>.*)')

def header_info(content):
    "Markdown heading (level, text) of `content`'s first line; (0, None) if not a heading"
    m = _re_hdr.match(content or '')
    return (len(m['level']), m['text']) if m else (0, None)

@patch
def header_level(self:Message):
    "Heading level of a heading note message, else 0"
    return header_info(self.content)[0] if self.msg_type==snote else 0

def section_msgs(ms, head):
    "`head` plus its section in `ms`: messages until the next heading of the same or higher level"
    lvl = head.header_level()
    if not lvl: return Msgs([head])
    ms, res = list(ms), [head]
    for m in ms[ms.index(head)+1:]:
        l = m.header_level()
        if l and l<=lvl: break
        res.append(m)
    return Msgs(res)

# %% ../nbs/00_dialog.ipynb #e074c630
@patch(as_prop=True)
def has_error(self:Message):
    if self.msg_type != scode: return False
    return any(o.get('output_type') == 'error' for o in (self.output or []))

def get_output_mds(output):
    "Extract text/markdown content from code outputs (display_data and execute_result)"
    if not output: return []
    return [o['data']['text/markdown'] for o in output
        if o.get('output_type') in ('display_data', 'execute_result') and 'text/markdown' in o.get('data', {})]

# %% ../nbs/00_dialog.ipynb #c09bb8be
def mk_jmsg(typ, metadata=None, **kwargs):
    "A minimal Jupyter iopub message dict of type `typ`, with `kwargs` as its content"
    kwargs['metadata'] = metadata or {}
    return {'msg_type':typ, 'content':kwargs, 'header':{'msg_type':typ}}

def mk_stream(text, name='stdout'): return mk_jmsg('stream', name=name, text=text)
def mk_error(ename='Exception', evalue='', traceback=None): return mk_jmsg('error', ename=ename, evalue=evalue, traceback=traceback or [])
def mk_dispdata(data, metadata=None, display_id=None):
    return mk_jmsg('display_data', data=data, metadata=metadata, transient={'display_id':display_id} if display_id else {})
def mk_execresult(data, metadata=None, execution_count=1):
    return mk_jmsg('execute_result', data=data, metadata=metadata, execution_count=execution_count)

def output_from_msg(jmsg):
    "ipynb output dict for the Jupyter iopub message dict `jmsg`"
    mt,c = jmsg['header']['msg_type'],jmsg['content']
    if mt=='stream': return dict(output_type=mt, name=c['name'], text=c['text'])
    if mt=='error': return dict(output_type=mt, ename=c['ename'], evalue=c['evalue'], traceback=c['traceback'])
    if mt in ('execute_result','display_data'):
        res = mk_output(mt, c['data'], c['metadata'])
        if mt=='execute_result': res['execution_count'] = c.get('execution_count')
        return res
    raise ValueError(f'Unrecognized output msg type: {mt!r}')

# %% ../nbs/00_dialog.ipynb #eb52bbdb
@patch
def clear_output(self:Message, wait=False):
    "Clear outputs now, or on the next `add_output` if `wait`"
    self._clear_pending = wait
    if not wait: self.output = [] if self.msg_type in (scode, sprompt) else ''

@patch
def add_output(self:Message,
    jmsg, # A Jupyter iopub message dict
    trunc=None, # Optional transform applied to each new output dict, e.g. truncation
    on_input=None, # Optional handler for kernel `input_request` messages
):
    "Convert iopub message `jmsg` to an output dict and add it to this message's outputs"
    if not self.output: self.output = []
    self.clear_out_cache()
    if getattr(self, '_clear_pending', False): self.clear_output()
    mt = jmsg['header']['msg_type']
    if mt=='execute_result' and self.content.rstrip().endswith(';'): return
    if mt=='input_request': return on_input(jmsg) if on_input else None
    display_id = nested_idx(jmsg, 'content', 'transient', 'display_id')
    if isupd := mt=='update_display_data':
        assert display_id
        jmsg['msg_type'] = jmsg['header']['msg_type'] = 'display_data'
    out = output_from_msg(jmsg)
    if trunc: out = trunc(out)
    if display_id: out['metadata']['did'] = display_id
    if isupd:
        for i,o in enumerate(self.output):
            if nested_idx(o, 'metadata', 'did')==display_id:
                self.output[i] = out
                return
    self.output.append(out)

# %% ../nbs/00_dialog.ipynb #08680316
@patch(as_prop=True)
def directives(self:Message):
    "nbdev directives from content comments and the meta `nbdev` dict, comments winning"
    return mk_cell(self.content, metadata=self.meta).directives

def _get_exported(self): return 'export' in self.directives or 'exports' in self.directives
def _set_exported(self, v):
    c = mk_cell(self.content, metadata=self.meta)
    d = c.directives
    val = d.get('export', d.get('exports'))
    c.directives = {k:x for k,x in d.items() if k not in ('export','exports')}
    if self.content != c.source: self.content = c.source
    if v: self.meta.setdefault('nbdev',{})['export'] = val or 'true'
Message.exported = property(_get_exported, _set_exported,
    doc="Whether this message carries an nbdev export directive, in content or meta; assigning writes the meta form, migrating any content directive")

def dlg2py(dlg):
    "The exported code of `dlg`, as a python source string"
    return '\n\n'.join(m.content for m in dlg.messages if m.msg_type==scode and m.exported)

# %% ../nbs/00_dialog.ipynb #0db3221b
_re_exp = re.compile(r'#\|\s*exports?[^\n]*\n')

def copy_export(s, src):
    "Prepend `src`'s leading export directive line to `s`, unless `s` already starts with a `#|` directive"
    m = _re_exp.match(src)
    return m.group(0)+s if m and not s.startswith('#|') else s

# %% ../nbs/00_dialog.ipynb #860657a4
@patch
def merge_content(self:Message,
    mtype:str, # The merge target's msg_type
):
    "This message's content contribution when merged into a `mtype` message; hosts override for their own conventions"
    if mtype==scode: return self.content
    if self.msg_type==sprompt: return f'## AI Prompt\n{self.content}\n## AI Response\n{self.ai_res}'
    if self.msg_type==scode: return f'```python\n{self.content}\n```'
    if self.msg_type==sraw: return f'```plaintext\n{self.content}\n```'
    return self.content

# %% ../nbs/00_dialog.ipynb #c201c787
def merge_metas(metas):
    "First-wins merge of cell metadata dicts, merging the `nbdev` directives dict one level deeper"
    res,nbd = {},{}
    for meta in metas:
        for k,v in (meta or {}).items():
            if k=='nbdev':
                for dk,dv in v.items(): nbd.setdefault(dk,dv)
            else: res.setdefault(k,v)
    if nbd: res['nbdev'] = nbd
    return res

def merge_parts(msgs, srcs=None):
    "Merged `(content, meta)` for combining `msgs` (optionally with per-message rendered `srcs`): later messages' directive lines fold into the merged meta, first message winning conflicts"
    if srcs is None: srcs = [m.content for m in msgs]
    cells = [mk_cell(s) for s in srcs]
    for c in cells[1:]: c.remove_directives()
    meta = merge_metas([{**m.meta, 'nbdev': {k: x or 'true' for k,x in m.directives.items()}} for m in msgs])
    nbd = {k:x for k,x in meta.get('nbdev',{}).items() if k not in cells[0].directives}
    if nbd: meta['nbdev'] = nbd
    else: meta.pop('nbdev', None)
    return '\n\n'.join(c.source for c in cells), meta

# %% ../nbs/00_dialog.ipynb #c872b4ee
_out_types = {'stream','display_data','execute_result','error'}

@patch
def validate(self:Message):
    "Raise `ValueError` for problems that would break saving or rendering; returns self if fine"
    if self.msg_type not in smsg_types: raise ValueError(f"{self.id}: unknown msg_type {self.msg_type!r}")
    if not (self.id and isinstance(self.id, str)): raise ValueError(f"message missing id: {truncstr(self.content, 30)!r}")
    if not isinstance(self.content, str): raise ValueError(f"{self.id}: content must be str")
    o = self.output
    if self.msg_type in (scode, sprompt):
        if not isinstance(o, list): raise ValueError(f"{self.id}: {self.msg_type} output must be a list")
        if bad := first(x for x in o if not (isinstance(x, dict) and x.get('output_type') in _out_types)):
            raise ValueError(f"{self.id}: bad output entry {truncstr(str(bad), 50)!r}")
    elif o: raise ValueError(f"{self.id}: {self.msg_type} message must not carry output")
    try: dumps(self.meta)
    except TypeError as e: raise ValueError(f"{self.id}: meta not JSON-serializable: {e}") from None
    return self

# %% ../nbs/00_dialog.ipynb #d07ccb3d
@patch
def validate(self:Dialog):
    "Validate every message plus dialog-scope rules (unique ids, serializable `meta`); returns self if fine"
    ids = [m.id for m in self.messages]
    if dups := {i for i in ids if ids.count(i)>1}: raise ValueError(f"duplicate message id(s): {', '.join(sorted(dups))}")
    for m in self.messages: m.validate()
    try: dumps(self.meta)
    except TypeError as e: raise ValueError(f"dialog meta not JSON-serializable: {e}") from None
    return self

# %% ../nbs/00_dialog.ipynb #1c03c386
def ruuid4():
    "Generate a deterministic UUID4-like string using rtoken_hex"
    parts = [rtoken_hex(4), rtoken_hex(2), rtoken_hex(2), rtoken_hex(2), rtoken_hex(6)]
    parts[2], parts[3] = '4' + parts[2][1:], format(random.randint(8, 11), 'x') + parts[3][1:]
    return f"{parts[0]}-{parts[1]}-{parts[2]}-{parts[3]}-{parts[4]}"

class Attachment(BasicRepr):
    def __init__(self, data:bytes, content_type:str, id:str=''):
        id = str(id) if id else ruuid4()
        store_attr()

add_id_hash(Attachment, 'id')

@patch
def mk_attachment(self:Message, data:bytes, content_type:str, id:str=''):
    att = Attachment(data=data, content_type=content_type, id=id)
    return self.attachments.append(att)

# %% ../nbs/00_dialog.ipynb #18689653
tiny_png = base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==')

# %% ../nbs/00_dialog.ipynb #036da886
@patch
def todict(self:Dialog): return {k:v for k,v in asdict(self).items() if k[0]!='_'}
