"""ChatGPT web conversations as dialogs

Convert ChatGPT web conversations into dialogs.

## Conversation payloads

The web app renders every conversation from a JSON payload, and three sources serve the same node schema: `GET /backend-api/conversation/<id>` (the owner's login), `GET /backend-api/share/<id>` (share links, including workspace `/share/e/` ones), and each conversation in the Settings data export. A node wraps a `message` carrying an `author` role, a typed `content`, a `recipient`, and `metadata`. `convo2dlg` converts any of these payloads; `url2convo` fetches one through a logged-in browser tab.

Docs: https://AnswerDotAI.github.io/llmsurgery/gpt.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_gpt.ipynb.

# %% auto #0
__all__ = ['convo_nodes', 'nodes2chat', 'convo2dlg', 'url2convo']

# %% ../nbs/07_gpt.ipynb #241f8954
import json, re
from fastcore.utils import *
from fastllm.chat import mk_msg
from aidialog.msg_parts import Msg, Text, Thinking, ToolUse, ToolResult
from aidialog.hist import chat2dlg

# %% ../nbs/07_gpt.ipynb #fc48158d
def convo_nodes(convo):
    "Conversation nodes in order: `linear_conversation` when present, else the `current_node` parent chain"
    if lin := convo.get('linear_conversation'): return L(lin)
    m,res,nid = convo['mapping'],[],convo.get('current_node')
    while nid:
        res.append(m[nid])
        nid = m[nid].get('parent')
    return L(reversed(res))

# %% ../nbs/07_gpt.ipynb #888a3ce2
def _ref_md(r):
    its = r.get('items') or []
    return ' ('+', '.join(f"[{i.get('title') or i['url']}]({i['url']})" for i in its)+')' if its else ''

def _splice_refs(txt, refs):
    "Replace citation markers in `txt` with markdown links, splicing at each ref's verified offsets"
    for r in sorted(refs or [], key=lambda r: -r['start_idx']):
        s,e = r['start_idx'],r['end_idx']
        if txt[s:e]==r.get('matched_text'): txt = txt[:s]+_ref_md(r)+txt[e:]
    return txt

def _content(msg):
    "A message's payload string, from whichever content shape, with citations spliced in"
    c = msg['content']
    txt = '\n\n'.join(p for p in c['parts'] if isinstance(p,str)) if 'parts' in c else c.get('text','')
    return _splice_refs(txt, (msg.get('metadata') or {}).get('content_references'))

def _is_convo(node):
    "Is `node` part of the conversation proper (vs hidden bookkeeping)?"
    msg = node.get('message')
    if not msg: return False
    if msg['author']['role']=='system' or (msg.get('metadata') or {}).get('is_visually_hidden_from_conversation'): return False
    return msg['content'].get('content_type') not in ('reasoning_recap','model_editable_context')

def nodes2chat(
    nodes, # Conversation nodes, e.g. from `convo_nodes`
):
    "Canonical messages for the conversation in `nodes`"
    msgs,tu = [],None
    for n in filter(_is_convo, nodes):
        msg = n['message']
        role,c = msg['author']['role'],msg['content']
        if role=='user': msgs.append(mk_msg(_content(msg)))
        elif role=='tool':
            kw = dict(id=tu.id,name=tu.name,arguments=tu.arguments) if tu else dict(id=msg['id'],name=msg['author'].get('name'))
            msgs.append(Msg(role='tool', content=[ToolResult(text=_content(msg), **kw)]))
        elif msg.get('recipient','all')!='all':
            tu = ToolUse(id=msg['id'], name=msg['recipient'], arguments=dict(input=_content(msg)))
            msgs.append(Msg(role='assistant', content=[tu]))
        elif c.get('content_type')=='thoughts':
            msgs.append(Msg(role='assistant', content=[Thinking(text='\n\n'.join(t.get('content','') for t in c.get('thoughts',[])))]))
        else: msgs.append(Msg(role='assistant', content=[Text(text=_content(msg))]))
    return msgs

# %% ../nbs/07_gpt.ipynb #c1497ca9
def convo2dlg(
    convo, # Conversation payload dict, or path to a saved .json
    name=None, # Dialog name; the conversation title if None
    mx=2000, # Maximum rendered tool string length
):
    "A ChatGPT conversation as a dialog, one prompt per user turn"
    if isinstance(convo,(str,Path)): convo = json.loads(Path(convo).read_text())
    return chat2dlg(nodes2chat(convo_nodes(convo)), name or convo.get('title') or 'conversation', mx=mx)

# %% ../nbs/07_gpt.ipynb #82c17ed6
_re_convo = re.compile(r'([0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12})')

def _api_path(url):
    "The backend-api path for a conversation or share `url`"
    return ('share/' if '/share/' in url else 'conversation/')+_re_convo.search(url).group(1)

async def url2convo(
    url, # Conversation or share URL (or bare conversation id)
    page, # A fastcdp `Page` in a logged-in browser
):
    "The conversation payload for `url`, fetched with the login held by `page`"
    if not await page.eval(r"location.host=='chatgpt.com'"): await page.goto('https://chatgpt.com')
    return await page.eval(f"""fetch('/api/auth/session').then(r=>r.json()).then(j=>
        fetch('/backend-api/{_api_path(url)}', {{headers:{{Authorization:'Bearer '+j.accessToken}}}}).then(r=>r.json()))""")
