"""Converting dialogs into LLM chat history

Docs: https://AnswerDotAI.github.io/llmsurgery/hist.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_hist.ipynb.

# %% auto #0
__all__ = ['AI_RENDERERS', 'UNSUPPORTED_MSG', 'join_out', 'render_output_ai', 'render_outputs_ai', 'ai_fmt', 'try_eval',
           'to_local_time', 'media_item', 'msgs2hist', 'dlg2canon']

# %% ../nbs/02_hist.ipynb #40ac6466
import re, base64, binascii, hashlib
from ast import literal_eval
from datetime import datetime
from zoneinfo import ZoneInfo
from itertools import chain

from fastcore.utils import *
from fastcore.ansi import strip_ansi
from fastcore.xtras import detect_mime
from fastcore.nbio import preferred_msg_out, concat_streams
from fastcore.xml import to_xml, Media, MediaUnavailable, Output, CellSource, Message as XMLMessage
from fastllm.chat import re_token, re_tools, MediaUrl, mk_msg, fmt2hist, Msg
from fastllm.types import PartType
from .dialog import *

# %% ../nbs/02_hist.ipynb #3d273a5c
def join_out(d):
    "Join Jupyter's list-of-lines output data into one string"
    return ''.join(d) if isinstance(d, list) else d

AI_RENDERERS = {  # chkstyle: ignore-node
    'text/plain': lambda d: strip_ansi(str(d)),
    'text/html': join_out,
    'text/markdown': join_out,
    'text/latex': join_out,
    'application/javascript': lambda d: f'<script>{join_out(d)}</script>',
}

# %% ../nbs/02_hist.ipynb #8885dfcc
def render_output_ai(out, renderers=None):
    "Plain-text rendering of one Jupyter output, as the AI sees it; `renderers` overrides/extends the per-mime table"
    r = AI_RENDERERS if renderers is None else AI_RENDERERS|renderers
    ptyp,d = preferred_msg_out(out, html1st=False, include_imgs=False)
    return r.get(ptyp, lambda d: '')(d)

def render_outputs_ai(outputs, renderers=None):
    "Plain-text rendering of a Jupyter output list for LLM context"
    if (not isinstance(outputs, (list,tuple))) or (outputs and not isinstance(outputs[0],dict)):
        print(f"Unexpected outputs: {outputs}")
        return ''
    return '\n'.join(render_output_ai(o, renderers=renderers) for o in concat_streams(outputs))

# %% ../nbs/02_hist.ipynb #6df26e0a
def ai_fmt(out, strip_tools=False):
    "Format AI response as it will be attached to the chat history"
    res = out
    if strip_tools:
        res = re_token.sub('', res)
        res = re_tools.sub('', res)
    res = res.strip().removesuffix("\n*[Response interrupted]*").strip()
    return res or '<output result="pending" reason="incomplete"/>'

# %% ../nbs/02_hist.ipynb #dbd5e19b
_prims = str, int, float, complex, bool, tuple, list, dict, set, frozenset

def try_eval(s, typ:str|None=None):
    "Like `literal_eval`, but wraps in dynamic class named `typ` if succeeds, and returns `s` if fails"
    try:
        res = literal_eval(s)
        if typ and isinstance(res, _prims): res = type(typ, (type(res),), {})(res)
        return res
    except: return s

# %% ../nbs/02_hist.ipynb #c299f49f
Message.ai_renderers = {}

@patch
def render_out(self:Message):
    "Compute and cache the for-AI rendering of this message's output"
    if self._ai_rend is not None: return
    if self.msg_type in (sprompt, scode):
        air = render_outputs_ai(self.output or [], renderers=self.ai_renderers)
        self._ai_rend = ai_fmt(air) if self.msg_type == sprompt else str(try_eval(air))
    else: self._ai_rend = ''

@patch(as_prop=True)
def ai_output(self:Message):
    self.render_out()
    return self._ai_rend

# %% ../nbs/02_hist.ipynb #6c897570
def to_local_time(time_str, tz='UTC'):
    "Convert ISO time string to local timezone"
    if not time_str: return ''
    try: dt = datetime.fromisoformat(time_str)
    except ValueError: return ''
    return dt.astimezone(ZoneInfo(tz)).isoformat()

@patch
def local_time(self:Message):
    "Localized `time_run` for hosts that stamp one; '' when absent"
    if not (t := getattr(self, 'time_run', '')): return ''
    tz = getattr(self.dlg, 'timezone', 'UTC') if self.dlg else 'UTC'
    return to_local_time(t, tz)

# %% ../nbs/02_hist.ipynb #9fe92c08
@patch
def todict(self:Message):
    res = AttrDict({k:v for k,v in asdict(self).items() if k[0]!='_' and k!='attachments'})
    res['output'] = self.ai_output
    return res

# %% ../nbs/02_hist.ipynb #dc9e55ab
def _mime_kind(mime):
    if mime == 'application/pdf': return 'pdf'
    return mime.split('/', 1)[0] if mime and mime.split('/', 1)[0] in {'image','audio','video'} else None

def _mime_supported(mime, aim_info):
    if   _mime_kind(mime) == 'image' and aim_info.get('supports_vision', False):      return True
    elif _mime_kind(mime) == 'video' and aim_info.get('supports_video_input', False): return True
    elif _mime_kind(mime) == 'audio' and aim_info.get('supports_audio_input', False): return True
    elif _mime_kind(mime) == 'pdf'   and aim_info.get('supports_pdf_input', False):   return True
    return False

# %% ../nbs/02_hist.ipynb #cab4286d
class _MissError(Exception): pass

UNSUPPORTED_MSG = "An unsupported media type was included in the context: {mime}. Please instruct the user to switch to a model that supports this media type."
Message.UNSUPPORTED_MSG = UNSUPPORTED_MSG

# %% ../nbs/02_hist.ipynb #8fde0964
def _media_xml(media_type, media_id, mime=None):
    "Create a media XML tag for LLM context."
    return to_xml(Media(id=media_id, type=media_type, mime=mime))

def _media_unavailable(media_type, media_id, e, mime=None):
    "Create a media-unavailable XML tag for LLM context."
    msg = "The user included this media, but it was not available to the AI. Tell the user that you cannot see it."
    return to_xml(MediaUnavailable(msg, id=str(media_id), type=media_type, reason=str(e), mime=mime))

def media_item(media_type, media_id, data, aim_info, mime=None, max_im_sz=None, prep=None, unavail_msg=UNSUPPORTED_MSG):
    "Load/prepare/package media, returning [xml_tag, data] or [media-unavailable]."
    try:
        # `data` can be bytes, or a function that loads bytes lazily.
        data = data() if callable(data) else data
        if data is None: raise _MissError("media data unavailable")
        if not isinstance(data, (bytes, MediaUrl)): raise _MissError(f"expected bytes or MediaUrl, got {type(data).__name__}")
        mime = mime or (detect_mime(data) if isinstance(data, bytes) else data.mime)
        if not mime: raise _MissError("unsupported or unknown media type")
        if not _mime_supported(mime, aim_info): raise _MissError(unavail_msg.format(mime=mime))
        # `media_id` can be a string, or a function that derives an id.
        media_id = media_id(data) if callable(media_id) else media_id
        if prep and isinstance(data, bytes): data = prep(data, mime, max_im_sz)
        return [_media_xml(media_type, media_id, mime), data]
    except (_MissError, OSError, binascii.Error) as e:
        media_id = getattr(media_id, '__name__', 'unknown') if callable(media_id) else media_id
        return [_media_unavailable(media_type, media_id, e, mime)]

# %% ../nbs/02_hist.ipynb #0fc50b6d
@patch
def prep_img(self:Message, data, mime, max_im_sz=None):
    "Prepare image bytes before they enter LLM context; the base class passes them through unchanged"
    return data

# %% ../nbs/02_hist.ipynb #c9792733
def _media_atts(msg, aim_info, max_im_sz=None):
    "Build media context from a message's attachments that are referenced in the content."
    attids = set()
    attids.update(re.findall(r'!\[[^\]]*\]\(attachment:([0-9a-f-]{36})\)', msg.content))
    attids.update(re.findall(r'<!-- last_output:([0-9a-f-]{36}) -->', msg.content))
    atts = L(msg.attachments).filter(lambda o: o in sorted(attids))
    return list(chain.from_iterable(media_item('content', o.id, o.data, aim_info=aim_info, max_im_sz=max_im_sz,
        prep=msg.prep_img, unavail_msg=msg.UNSUPPORTED_MSG) for o in atts))

# %% ../nbs/02_hist.ipynb #91cbca46
def _img_id(im_bytes):
    "Generate a deterministic 8 char id from `im_bytes`"
    h = hashlib.md5(im_bytes)
    return base64.b32encode(h.digest()).decode('utf-8')[:8]

# %% ../nbs/02_hist.ipynb #08035646
def _img_item(pair, m, aim_info, max_im_sz):
    mime,data = pair
    return media_item('output', _img_id, partial(base64.b64decode, data), aim_info, mime, max_im_sz, prep=m.prep_img, unavail_msg=m.UNSUPPORTED_MSG)
    
def _img_output(m, aim_info, max_im_sz):
    "Extract any image outputs from `m` and return a list of encoded images and their xml tags."
    pairs = L(m.output or []).attrgot('data', {}).flatmap(dict.items).filter(lambda p: p[0] in {'image/jpeg','image/png'})
    return pairs.flatmap(_img_item, m=m, aim_info=aim_info, max_im_sz=max_im_sz)

# %% ../nbs/02_hist.ipynb #04616fe6
@patch
def _xml_content(self:Message):
    "Get content elements for XML"
    return [CellSource(self.content)]

# %% ../nbs/02_hist.ipynb #601875c5
@patch
def prompt_txt(self:Message, last=False):
    "History text for a prompt message: the content, bare. Hosts patch this to add their own envelope"
    return self.content

@patch
def to_xml(self:Message, last=False):
    "Create XML representation of this message"
    if self.msg_type == 'prompt': return self.prompt_txt(last)
    elems = [CellSource(self.content) if self.content else "", Output(self.ai_output) if self.ai_output else ""]
    return to_xml(XMLMessage(*elems, type=self.msg_type, id=self.id, time=self.local_time()), do_escape=False)

# %% ../nbs/02_hist.ipynb #e0542c55
@patch
def media_extra(self:Message, aim_info, max_im_sz=None):
    "Additional media sources contributed by subclasses (e.g. app-specific file references)"
    return []

@patch
def to_media(self:Message, aim_info, max_im_sz=None):
    "Aggregate media from attachments, `media_extra`, and code outputs"
    media_ctx = []
    if media_atts := _media_atts(self, aim_info, max_im_sz): media_ctx += media_atts
    if extra := self.media_extra(aim_info, max_im_sz): media_ctx += extra
    if self.msg_type == scode:
        if img_outputs := _img_output(self, aim_info, max_im_sz): media_ctx += img_outputs
    return media_ctx

# %% ../nbs/02_hist.ipynb #afd617d8
@patch
def to_parts(self:Message, aim_info:dict, last=False):
    "Convert message to a list of history parts: media, then XML text."
    parts = []
    if media := self.to_media(aim_info): parts.extend(media)
    if mxml := self.to_xml(last): parts.append(mxml)
    return parts

# %% ../nbs/02_hist.ipynb #0b6318f6
def msgs2hist(msgs:list[Message], aim_info:dict):
    "Convert messages to LLM history. `msgs` must end with a prompt, which renders with `last=True`."
    if msgs[-1].msg_type != sprompt: raise ValueError("msgs2hist requires msgs to end with a prompt")
    res = []
    for is_first, m in loop_first(reversed(msgs)):
        if m.msg_type == sprompt: res += [m.ai_output, m.to_parts(aim_info, last=is_first)]
        else: res[-1] = m.to_parts(aim_info) + res[-1]
    return res[::-1]

# %% ../nbs/02_hist.ipynb #22d1bb97
def _explode(a, t):
    "One call/result pair per tool use in a batched assistant/tool pair"
    tus = [p for p in a.content if p.type==PartType.tool_use]
    if len(tus)<2: return [a,t]
    pre,trs = [p for p in a.content if p.type!=PartType.tool_use],{p.data['id']:p for p in t.content}
    res = []
    for is_first,tu in loop_first(tus):
        res += [Msg(role='assistant', content=(pre if is_first else [])+[tu]), Msg(role='tool', content=[trs[tu.data['id']]])]
    return res

def _seq_tools(msgs):
    "Explode batched tool calls into strict call/result alternation"
    out = []
    for m in msgs:
        if m.role=='tool' and out and out[-1].role=='assistant': out += _explode(out.pop(), m)
        else: out.append(m)
    return out

# %% ../nbs/02_hist.ipynb #4eccdf09
def dlg2canon(
    dlg, # A `Dialog`, ending with a prompt
    aim_info=None, # Model capability dict for media handling; images enabled if None
):
    "Canonical fastllm messages for `dlg`, with each reply's tool calls recovered as real parts"
    hist = msgs2hist(dlg.messages, dict(supports_vision=True) if aim_info is None else aim_info)
    msgs = []
    for i,t in enumerate(hist):
        if i%2==0: msgs.append(mk_msg(t))
        else: msgs += _seq_tools(fmt2hist(t))
    ids = [p.data['id'] for m in msgs for p in m.content if p.type==PartType.tool_use]
    if dups := {i for i in ids if ids.count(i)>1}: raise ValueError(f"duplicate tool call id(s): {', '.join(sorted(dups))}")
    return msgs
