"""Reading and writing dialogs as Jupyter notebooks

Docs: https://AnswerDotAI.github.io/llmsurgery/ipynb.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_ipynb.ipynb.

# %% auto #0
__all__ = ['reply_sep', 'att2dict', 'split_cell_src', 'get_ipynb', 'write_ipynb', 'ipynb_cells', 'dict2att', 'read_ipynb']

# %% ../nbs/01_ipynb.ipynb #d3d0463b
from fastcore.utils import *
from fastcore.xtras import atomic_save
import nbformat,json
from nbformat.v4 import new_markdown_cell as new_md, new_code_cell as new_code, new_raw_cell as new_raw, new_notebook
from base64 import b64encode,b64decode
from nbformat.validator import NotebookValidationError
from nbformat.reader import NotJSONError
from .dialog import *

# %% ../nbs/01_ipynb.ipynb #aaaeb85a
def att2dict(att): return {att.content_type: b64encode(att.data).decode('ascii') if isinstance(att.data, bytes) else att.data}

# %% ../nbs/01_ipynb.ipynb #3fde3c72
reply_sep = "\n\n##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->\n\n"

def split_cell_src(cell):
    "Split cell source into (content, ai_reply_or_None)"
    content, *reply = cell.get('source', '').split(reply_sep)
    return content, (reply[0] if reply else None)

# %% ../nbs/01_ipynb.ipynb #58354f4a
_out_meta_skip = {'__type'}

def _clean_out_meta(o):
    if m := o.get('metadata'): o['metadata'] = {k:v for k,v in m.items() if k not in _out_meta_skip}
    return o

# %% ../nbs/01_ipynb.ipynb #20f31fdc
@patch
def cell_meta(self:Message):
    "Metadata dict to write: `meta` plus demoted `meta_attrs` fields, falsy values omitted"
    meta = dict(self.meta)
    for a,k in self.meta_attrs.items():
        if (v := getattr(self, a, None)): meta[k] = v
        else: meta.pop(k, None)
    return meta

# %% ../nbs/01_ipynb.ipynb #0dde746d
@patch
def to_cell(self:Message, version=2):
    "Convert message to an nbformat cell"
    meta = self.cell_meta()
    cts = self.content or ''
    f = new_md if self.msg_type in (snote,sprompt) else new_code if self.msg_type == scode else new_raw
    if self.msg_type==sprompt:
        meta['solveit_ai'] = True
        if o := self.ai_res: cts = cts + reply_sep + o
    outkw = {}
    if self.msg_type==scode and self.output:
        outputs = self.output
        if version==1: outputs = json.loads(outputs)
        outkw['outputs'] = [nbformat.from_dict(_clean_out_meta(o)) for o in outputs]
    atts = {att.id: att2dict(att) for att in (self.attachments or [])}
    if atts and self.msg_type in (sprompt,snote): outkw['attachments'] = atts
    id_ = self.id[1:]
    try: return f(cts, id=id_, metadata=meta, **outkw)
    except NotebookValidationError as e:
        print(f"NB validation err: {e}")
        outkw['outputs'] = [] if self.msg_type == scode else ''
        return f(cts, id=id_, metadata=meta, **outkw)

# %% ../nbs/01_ipynb.ipynb #10a73cfc
def get_ipynb(dlg:Dialog, version=2, msgs=None):
    "Notebook object for `dlg`; `msgs` defaults to all its messages"
    cells = [m.to_cell(version=version) for m in (dlg.messages if msgs is None else msgs)]
    return new_notebook(cells=cells, metadata=dict(dlg.meta))


# %% ../nbs/01_ipynb.ipynb #ea5fa1dd
def write_ipynb(dlg:Dialog, fname=None, version=2, msgs=None, **kwargs):
    "Write `dlg` as a notebook, or return the JSON string if `fname` is None; `kwargs` (e.g. `uid`/`gid`) pass to `atomic_save`"
    nb = get_ipynb(dlg, version=version, msgs=msgs)
    if not fname: return nbformat.writes(nb, indent=2)
    with atomic_save(Path(fname), mode='w', encoding='utf-8', **kwargs) as f: nbformat.write(nb, f)

# %% ../nbs/01_ipynb.ipynb #5527e596
@patch
def write(self:Dialog, base_path, version=2, msgs=None, **kwargs):
    write_ipynb(self, Path(base_path)/f'{self.name}.ipynb', version=version, msgs=msgs, **kwargs)

# %% ../nbs/01_ipynb.ipynb #0e16e93a
def ipynb_cells(path, nm, prefix=None, suffix=None):
    tmpl = path/f'{nm}.ipynb'
    if not tmpl.exists(): return []
    try: cells = nbformat.read(tmpl, as_version=nbformat.NO_CONVERT).cells
    except NotJSONError: return []
    return listify(prefix) + cells + listify(suffix)

# %% ../nbs/01_ipynb.ipynb #ba0bb61e
def dict2att(att_id, att_data):
    "Convert attachment dict to Attachment object"
    content_type, data = first(att_data.items())
    if isinstance(data, str): data = b64decode(data)
    return Attachment(data, content_type, att_id)

def _output_from_cell(cell):
    if cell.cell_type!='code': return ''
    return [nbformat.from_dict(o) for o in getattr(cell, 'outputs', [])]

# %% ../nbs/01_ipynb.ipynb #1b43e94f
@patch
def cell2msg(self:Dialog, cell):
    "Convert single notebook cell to message object"
    meta = dict(cell.metadata)
    kwargs = {a: meta.pop(k) for a,k in self.msg_cls.meta_attrs.items() if k in meta}
    content, reply = split_cell_src(cell)
    msg_type = sprompt if meta.pop('solveit_ai', 0) else snote if cell.cell_type=='markdown' else cell.cell_type
    output = ('' if msg_type in (snote,sraw)
        else _output_from_cell(cell) if msg_type == scode
        else prompt_output(reply) if reply else [])
    atts = [dict2att(att_id, att_data) for att_id, att_data in cell.get('attachments', {}).items()]
    id = '_' + (getattr(cell, 'id', None) or rtoken_hex(4))
    return self.msg_cls(content, id=id, output=output, msg_type=msg_type, dlg=self, attachments=atts, meta=meta, **kwargs)

# %% ../nbs/01_ipynb.ipynb #aef05275
@patch
def from_cells(self:Dialog, cells):
    self.messages = L(cells).map(self.cell2msg)
    return self

def read_ipynb(fname, cls=Dialog, name=None):
    "Read a dialog from notebook file `fname` (`.ipynb` added if missing), constructing via `cls`; `name` defaults to the file stem"
    f = Path(fname)
    if f.suffix != '.ipynb': f = f.with_suffix('.ipynb')
    if not f.exists(): return print(f,'does not exist')
    try: nb = nbformat.read(f, as_version=nbformat.NO_CONVERT)
    except (NotJSONError, nbformat.ValidationError, PermissionError): return
    return cls(name or f.stem, meta=dict(nb.get('metadata', {}))).from_cells(nb.cells)
