"""An ipynb mirror of every session transcript, so the dialog tools work on whole conversation histories

Finding an old discussion means searching conversations, but transcripts are JSONL full of envelope noise, and each host stores them differently. The mirror solves this by convergence: every Claude session and Codex thread is kept as an ordinary dialog ipynb under one root, so `nbrg` searches all history at once, and `find_msgs`, `summary_dlg`, and `view_msg` read any hit -- transcript handling becomes exactly as convenient as dialog handling, on both hosts, and inherits every future improvement to those tools.

The division of labor is: filename is identity (the mirror keeps the transcript's relative path and stem), mtime is sync (each mirror carries its source's mtime, so staleness is a pure stat comparison), and meta is truth (nb-level meta records host, source path, and the conversation's real time span; each message's meta carries its source record's `created` time and `uid`, and ids are deterministic, so hits stay citable across regenerations). Mirrors live under XDG state (not cache: `index` keeps mirrors whose transcript was garbage-collected, so the mirror doubles as an archive, and cache directories are fair game for cleanup tools).

Docs: https://AnswerDotAI.github.io/llmsurgery/mirror.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_mirror.ipynb.

# %% auto #0
__all__ = ['MIRROR', 'transcripts', 'mirror_path', 'mirror_sess', 'index', 'sess_index']

# %% ../nbs/06_mirror.ipynb #e376676d
import os
from fastcore.utils import *
from fastcore.script import call_parse
from fastcore.xdg import xdg_state_home
from aidialog.ipynb import write_ipynb
from . import ant, oai
from .sess import path_dlg

# %% ../nbs/06_mirror.ipynb #3b730eb8
MIRROR = xdg_state_home()/'llmsurgery'/'mirror'

def transcripts(
    ant_root=None, # Claude sessions store; `ant.SESSIONS` if None
    codex_home=None, # Codex home; `oai.CODEX_HOME` if None
):
    "Every transcript in both hosts' stores, as `(host, store, path)` rows"
    astore,ostore = Path(ant_root or ant.SESSIONS),Path(codex_home or oai.CODEX_HOME)/'sessions'
    return (L(('ant', astore, p) for p in sorted(astore.glob('*/*.jsonl')))
        + L(('oai', ostore, p) for p in sorted(ostore.glob('*/*/*/*.jsonl'))))

# %% ../nbs/06_mirror.ipynb #4340d65d
def mirror_path(
    host, # `'ant'` or `'oai'`
    store, # The store root `path` was found under
    path, # Transcript path
    root=None, # Mirror root; `MIRROR` if None
):
    "Where the transcript at `path` mirrors to"
    return Path(root or MIRROR)/host/Path(path).relative_to(store).with_suffix('.ipynb')

def mirror_sess(
    host, # `'ant'` or `'oai'`
    store, # The store root `path` was found under
    path, # Transcript path
    root=None, # Mirror root; `MIRROR` if None
):
    "Write the dialog mirror of the transcript at `path`, stamping the source's mtime; returns the mirror's path"
    dest = mirror_path(host, store, path, root)
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix('.tmp')
    write_ipynb(path_dlg(host, Path(path)), tmp)
    os.replace(tmp, dest)
    st = Path(path).stat()
    os.utime(dest, ns=(st.st_atime_ns, st.st_mtime_ns))
    return dest

# %% ../nbs/06_mirror.ipynb #5a370152
def index(
    root=None, # Mirror root; `MIRROR` if None
    ant_root=None, # Claude sessions store; `ant.SESSIONS` if None
    codex_home=None, # Codex home; `oai.CODEX_HOME` if None
    force=False, # Rebuild every mirror, e.g. after the conversion logic changes?
    verbose=False, # Print each rebuilt mirror?
):
    "Sync the mirror with both hosts' stores: rebuild stale, keep orphans, collect failures; the result carries the mirror `root`"
    built,fresh,failed = L(),0,L()
    for host,store,p in transcripts(ant_root, codex_home):
        d = mirror_path(host, store, p, root)
        if not force and d.exists() and d.stat().st_mtime_ns == p.stat().st_mtime_ns:
            fresh += 1
            continue
        try:
            built.append(mirror_sess(host, store, p, root))
            if verbose: print(built[-1])
        except Exception as e: failed.append((p, e))
    return AttrDict(built=built, fresh=fresh, failed=failed, root=Path(root or MIRROR))

@call_parse
def sess_index(
    force:bool=False, # Rebuild every mirror, e.g. after the conversion logic changes?
    verbose:bool=False, # Print each rebuilt mirror?
):
    "Sync the session mirror at `MIRROR`"
    res = index(force=force, verbose=verbose)
    print(f'{len(res.built)} rebuilt, {res.fresh} fresh, {len(res.failed)} failed')
    for p,e in res.failed: print(f'FAIL {p}: {e}')
