"""Build, inspect, and fork synthetic Codex sessions

Docs: https://AnswerDotAI.github.io/llmsurgery/oai.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_oai.ipynb.

# %% auto #0
__all__ = ['CODEX_HOME', 'codex_msg', 'codex_call', 'codex_output', 'tool_turn', 'rollout_file', 'load_rollout', 'response_items',
           'item_txt', 'strip_reasoning', 'reid_items', 'curate_items', 'CodexAppServer', 'dlg2items', 'dlg2thread']

# %% ../nbs/04_oai.ipynb #435247a5
import asyncio, json, os, uuid
from pathlib import Path
from fastcore.utils import *
from fastllm.openai_responses import denorm_msgs
from .hist import dlg2chat

# %% ../nbs/04_oai.ipynb #cc829280
def codex_msg(role, text):
    "A Responses API message item"
    typ = 'input_text' if role=='user' else 'output_text'
    return dict(type='message', role=role, content=[dict(type=typ, text=text)])

def codex_call(name, arguments, call_id=None):
    "A Responses API function call item"
    return dict(type='function_call', name=name, arguments=json.dumps(arguments), call_id=call_id or 'call_'+uuid.uuid4().hex)

def codex_output(call_id, output):
    "The result of a Responses API function call"
    return dict(type='function_call_output', call_id=call_id, output=output)

def tool_turn(prompt, name, arguments, output, answer):
    "A complete synthetic tool-use turn"
    call = codex_call(name, arguments)
    return [codex_msg('user', prompt), call, codex_output(call['call_id'], output), codex_msg('assistant', answer)]

# %% ../nbs/04_oai.ipynb #103b6857
CODEX_HOME = Path.home()/'.codex'

def rollout_file(thread_id, codex_home=CODEX_HOME):
    "The persisted rollout for `thread_id`, if it exists"
    return first((Path(codex_home)/'sessions').rglob(f'*{thread_id}.jsonl'))

def load_rollout(thread_id, codex_home=CODEX_HOME):
    "Read the JSONL rollout for `thread_id`"
    return L(dict2obj(json.loads(line)) for line in rollout_file(thread_id, codex_home).read_text().splitlines())

# %% ../nbs/04_oai.ipynb #3ff14123
def response_items(recs):
    "Extract the model-visible Responses API items from rollout records"
    return L(obj2dict(r)['payload'] for r in recs if r.get('type')=='response_item')

def _item_txts(o):
    if isinstance(o, str): yield o
    elif isinstance(o, dict): yield from (t for v in o.values() for t in _item_txts(v))
    elif is_listy(o): yield from (t for x in o for t in _item_txts(x))

def item_txt(item):
    "Every string in a Responses API item, joined, for finding captured items by text"
    return '\n'.join(_item_txts(obj2dict(item)))

# %% ../nbs/04_oai.ipynb #2bb9c777
def strip_reasoning(items):
    "Drop Responses API `reasoning` items; replay does not need them"
    return L(items).filter(lambda o: o.get('type')!='reasoning')

def _reid(prefix, key): return prefix+'_'+uuid.uuid5(uuid.NAMESPACE_URL, key).hex

def reid_items(items, key=''):
    "Deterministically re-derive response item and paired call ids, returning fresh dicts"
    items,ids = [obj2dict(o) for o in items],{}
    for i,o in enumerate(items):
        for field in ('id', 'call_id'):
            old = o.get(field)
            if old and old not in ids: ids[old] = _reid(old.partition('_')[0], f'{key}:{i}:{field}')
    def _remap(o):
        if isinstance(o, str): return ids.get(o, o)
        if isinstance(o, dict): return {k:_remap(v) for k,v in o.items()}
        if is_listy(o): return [_remap(v) for v in o]
        return o
    return L(_remap(o) for o in items)

def curate_items(recs, key=''):
    "Extract, strip reasoning from, and re-identify captured rollout records"
    return reid_items(strip_reasoning(response_items(recs)), key)

# %% ../nbs/04_oai.ipynb #f7fc9b42
class CodexAppServer:
    "A small async client for `codex app-server`"
    def __init__(self, cmd='codex', codex_home=None):
        self.cmd,self.codex_home = cmd,codex_home
        self.proc,self._id,self.events = None,0,[]

    async def start(self):
        env = os.environ.copy()
        if self.codex_home is not None: env['CODEX_HOME'] = str(self.codex_home)
        self.proc = await asyncio.create_subprocess_exec(self.cmd, 'app-server', stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL, env=env)
        await self.request('initialize', dict(clientInfo=dict(name='fastllm_claude_code', title='fastllm-claude-code', version='0.1')))
        await self.notify('initialized')
        return self

    async def _send(self, message):
        self.proc.stdin.write((json.dumps(message)+'\n').encode())
        await self.proc.stdin.drain()

    async def notify(self, method, params=None): await self._send(dict(method=method, params=params or {}))

    async def request(self, method, params=None):
        self._id += 1
        await self._send(dict(method=method, id=self._id, params=params or {}))
        while line := await self.proc.stdout.readline():
            message = json.loads(line)
            if message.get('id') != self._id:
                self.events.append(message)
                continue
            if 'error' in message: raise RuntimeError(message['error']['message'])
            return dict2obj(message['result'])
        raise RuntimeError('codex app-server exited before replying')

    async def start_thread(self, cwd=None, **kwargs):
        "Start a persisted thread"
        if cwd is not None: kwargs['cwd'] = str(Path(cwd).resolve())
        return (await self.request('thread/start', kwargs)).thread

    async def inject_items(self, thread_id, items):
        "Append Responses API `items` to a loaded thread's history"
        return await self.request('thread/inject_items', dict(threadId=thread_id, items=list(items)))

    async def create_thread(self, items, cwd=None, **kwargs):
        "Start a thread whose history is pre-filled with Responses API `items`"
        thread = await self.start_thread(cwd=cwd, **kwargs)
        await self.inject_items(thread.id, items)
        return thread
    async def fork_thread(self, thread_id, last_turn_id=None, **kwargs):
        "Fork a thread, optionally only through `last_turn_id`"
        params = dict(threadId=thread_id, **kwargs)
        if last_turn_id is not None: params['lastTurnId'] = last_turn_id
        return (await self.request('thread/fork', params)).thread

    async def close(self):
        if self.proc is not None and self.proc.returncode is None:
            self.proc.terminate()
            await self.proc.wait()

    async def __aenter__(self): return await self.start()
    async def __aexit__(self, *args): await self.close()

# %% ../nbs/04_oai.ipynb #78873705
def dlg2items(
    dlg, # A `Dialog`, ending with a prompt
    aim_info=None, # Model capability dict for media handling; images enabled if None
):
    "Responses API items for `dlg`, with each reply's tool calls recovered as real items"
    return denorm_msgs(dlg2chat(dlg, aim_info))

async def dlg2thread(
    dlg, # The dialog to convert
    cwd=None, # Project directory for the thread; the current directory if None
    codex_home=None, # Codex home; `~/.codex` if None
    **kwargs, # Passed to `thread/start`
):
    "Create a persisted Codex thread whose history is `dlg`, returning the thread id for `codex resume`"
    async with CodexAppServer(codex_home=codex_home) as app:
        thread = await app.create_thread(reid_items(dlg2items(dlg), dlg.name), cwd=cwd, **kwargs)
    return thread.id
