"""Read, write, and build Codex session rollouts

Docs: https://AnswerDotAI.github.io/llmsurgery/oai.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_oai.ipynb.

# %% auto #0
__all__ = ['CODEX_HOME', 'cur_thread', 'rollout_file', 'load_recs', 'load_rollout', 'project_thread', 'thread_id',
           'response_items', 'split_compaction', 'active_items', 'codex_msg', 'codex_call', 'codex_output',
           'parse_exec', 'exec_input', 'codex_custom_call', 'codex_custom_output', 'reid_items', 'CodexAppServer',
           'tool_turn', 'custom_turn', 'item_txt', 'item_role', 'conv_items', 'ItemHits', 'item_search', 'show_items',
           'PromptHist', 'prompt_hist', 'strip_reasoning', 'trunc_tools', 'curate_items', 'dlg2items', 'dlg2thread',
           'items2chat', 'chat2dlg', 'items2dlg', 'thread2dlg', 'resolve_thread']

# %% ../nbs/04_oai.ipynb #d29693fa
import asyncio, base64, json, os, re, uuid
from pathlib import Path
from fastcore.utils import *
from fastllm.openai_responses import denorm_msgs
from fastllm.chat import Msg, Part, PartType, hist2fmt, data_url
from .hist import dlg2chat
from .dialog import *
import json5

# %% ../nbs/04_oai.ipynb #fd091c3b
CODEX_HOME = Path.home()/'.codex'

def cur_thread():
    "The current Codex thread id, when running inside Codex"
    return os.environ.get('CODEX_THREAD_ID')

# %% ../nbs/04_oai.ipynb #6030ebfe
def rollout_file(
    thread_id, # Thread UUID
    codex_home=CODEX_HOME, # Codex home containing sessions
):
    "The persisted rollout for `thread_id`, if it exists"
    return first((Path(codex_home)/'sessions').rglob(f'*{thread_id}.jsonl'))

# %% ../nbs/04_oai.ipynb #e83e0de0
def load_recs(path):
    "Rollout records read directly from JSONL `path`"
    return L(dict2obj(json.loads(line)) for line in Path(path).read_text().splitlines())

# %% ../nbs/04_oai.ipynb #55005587
def load_rollout(
    thread_id=None, # Thread UUID; `cur_thread()` if None
    codex_home=CODEX_HOME, # Codex home containing sessions
):
    "The records of a persisted Codex thread"
    thread_id = thread_id or cur_thread()
    path = rollout_file(thread_id, codex_home)
    if not path: raise FileNotFoundError(f'No rollout for thread {thread_id!r}')
    return load_recs(path)

# %% ../nbs/04_oai.ipynb #391dbebf
def project_thread(
    cwd='.', # Project directory
    codex_home=CODEX_HOME, # Codex home containing sessions
):
    "The newest `(thread_id, rollout_path)` for `cwd`"
    cwd = Path(cwd).resolve()
    paths = sorted((Path(codex_home)/'sessions').rglob('*.jsonl'),key=lambda p:p.stat().st_mtime,reverse=True)
    for path in paths:
        meta = json.loads(path.open().readline())
        if meta['type']=='session_meta' and Path(meta['payload']['cwd']).resolve()==cwd: return meta['payload']['id'],path
    raise FileNotFoundError(f'No Codex thread for {cwd}')

# %% ../nbs/04_oai.ipynb #b03dc5aa
def thread_id(
    recs, # Rollout records
):
    "The owning thread id from the first session metadata record"
    return first(r.payload.get('id') for r in recs if r.get('type')=='session_meta')

# %% ../nbs/04_oai.ipynb #2c8c59eb
def response_items(
    recs, # Rollout records
):
    "Every Responses API item recorded in `recs`, including superseded history"
    return L(obj2dict(r.payload) for r in recs if r.get('type')=='response_item')

def split_compaction(
    recs, # Rollout records
):
    "The latest native replacement history and response items recorded after it"
    idxs = [i for i,r in enumerate(recs) if r.get('type')=='compacted']
    if not idxs: return L(),response_items(recs)
    i = idxs[-1]
    prior = L(obj2dict(x) for x in recs[i].payload.replacement_history)
    return prior,response_items(recs[i+1:])

def active_items(
    recs, # Rollout records
):
    "The Responses API history Codex reconstructs from `recs`"
    prior,new = split_compaction(recs)
    return prior+new

# %% ../nbs/04_oai.ipynb #4562f106
def codex_msg(role, text):
    "A Responses API message item"
    typ = 'input_text' if role in ('user','developer','system') else 'output_text'
    content = text if is_listy(text) else [dict(type=typ, text=text)]
    return dict(type='message', role=role, content=content)

def codex_call(name, arguments, call_id=None):
    "A Responses API function call item"
    return dict(type='function_call', name=name, arguments=json.dumps(arguments), call_id=call_id or 'call_'+uuid.uuid4().hex)

def codex_output(call_id, output):
    "The result of a Responses API function call"
    return dict(type='function_call_output', call_id=call_id, output=output)

# %% ../nbs/04_oai.ipynb #a2e139af
_re_exec = re.compile(r'^\s*const\s+(\w+)\s*=\s*await\s+tools\.([A-Za-z_]\w*)\((\{.*\})\);\s*text\((?:\1\.output|JSON\.stringify\(\1\))\);?\s*$', re.S)

def parse_exec(src):
    "The logical nested tool call in a simple Codex `exec` input, or None"
    m = _re_exec.match(src)
    if not m: return None
    try: arguments = json5.loads(m.group(3))
    except ValueError: return None
    return AttrDict(name='tools.'+m.group(2), arguments=arguments)

def exec_input(name, arguments):
    "Stable `exec` JavaScript for one logical `tools.*` call"
    assert name.startswith('tools.')
    tool = name.removeprefix('tools.')
    result = 'JSON.stringify(r)' if tool=='exec_command' else 'r.output'
    return f"const r = await tools.{tool}({json.dumps(arguments, separators=(',',':'))});\ntext({result});\n"

def codex_custom_call(name, arguments, call_id=None, item_id=None):
    "A Codex custom `exec` call wrapping one logical `tools.*` operation"
    call_id = call_id or 'call_'+uuid.uuid4().hex
    return dict(type='custom_tool_call', name='exec', input=exec_input(name, arguments), call_id=call_id,
        id=item_id or 'ctc_'+uuid.uuid4().hex, status='completed')

def codex_custom_output(call_id, output):
    "The result of a Codex custom tool call"
    if isinstance(output, str): output = [dict(type='input_text', text=output)]
    return dict(type='custom_tool_call_output', call_id=call_id, output=output)

# %% ../nbs/04_oai.ipynb #23599a7d
def _reid(prefix, key): return prefix+'_'+uuid.uuid5(uuid.NAMESPACE_URL, key).hex

def reid_items(
    items, # Responses API items
    key='', # Salt for deterministic IDs
):
    "Copies of `items` with response item and paired call IDs re-derived"
    items,ids = [obj2dict(o) for o in items],{}
    for i,o in enumerate(items):
        for field in ('id','call_id'):
            old = o.get(field)
            if old and old not in ids: ids[old] = _reid(old.partition('_')[0], f'{key}:{i}:{field}')
    def _remap(o):
        if isinstance(o, str): return ids.get(o,o)
        if isinstance(o, dict): return {k:_remap(v) for k,v in o.items()}
        if is_listy(o): return [_remap(v) for v in o]
        return o
    return L(_remap(o) for o in items)

# %% ../nbs/04_oai.ipynb #f4fffe3a
class CodexAppServer:
    "Small async client for `codex app-server`"
    def __init__(self, cmd='codex', codex_home=None):
        self.cmd,self.codex_home = cmd,codex_home
        self.proc,self._id,self.events = None,0,[]

    async def start(self):
        env = os.environ.copy()
        if self.codex_home is not None: env['CODEX_HOME'] = str(self.codex_home)
        self.proc = await asyncio.create_subprocess_exec(self.cmd, 'app-server', stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL, env=env)
        await self.request('initialize', dict(clientInfo=dict(name='llmsurgery', title='llmsurgery', version='0.1')))
        await self.notify('initialized')
        return self

    async def _send(self, message):
        self.proc.stdin.write((json.dumps(message)+'\n').encode())
        await self.proc.stdin.drain()

    async def notify(self, method, params=None): await self._send(dict(method=method, params=params or {}))

    async def request(self, method, params=None):
        self._id += 1
        await self._send(dict(method=method, id=self._id, params=params or {}))
        while line := await self.proc.stdout.readline():
            message = json.loads(line)
            if message.get('id') != self._id:
                self.events.append(message)
                continue
            if 'error' in message: raise RuntimeError(message['error']['message'])
            return dict2obj(message['result'])
        raise RuntimeError('codex app-server exited before replying')

    async def start_thread(self, cwd=None, **kwargs):
        "Start a persisted thread"
        if cwd is not None: kwargs['cwd'] = str(Path(cwd).resolve())
        return (await self.request('thread/start', kwargs)).thread

    async def resume_thread(self, thread_id, **kwargs):
        "Load a persisted thread into this app-server"
        return (await self.request('thread/resume', dict(threadId=thread_id, **kwargs))).thread

    async def read_thread(self, thread_id, include_turns=True):
        "Read persisted thread metadata and optional model turns"
        return (await self.request('thread/read', dict(threadId=thread_id, includeTurns=include_turns))).thread

    async def inject_items(self, thread_id, items):
        "Append raw Responses API `items` to a loaded thread's model history"
        return await self.request('thread/inject_items', dict(threadId=thread_id, items=list(items)))

    async def create_thread(self, items, cwd=None, **kwargs):
        "Start a thread whose history is pre-filled with `items`"
        thread = await self.start_thread(cwd=cwd, **kwargs)
        await self.inject_items(thread.id, items)
        return thread

    async def append_thread(self, thread_id, items, **kwargs):
        "Resume `thread_id` and append raw Responses items"
        thread = await self.resume_thread(thread_id, **kwargs)
        await self.inject_items(thread.id, items)
        return thread

    async def fork_thread(self, thread_id, last_turn_id=None, **kwargs):
        "Fork a thread, optionally only through `last_turn_id`"
        params = dict(threadId=thread_id, **kwargs)
        if last_turn_id is not None: params['lastTurnId'] = last_turn_id
        return (await self.request('thread/fork', params)).thread

    async def name_thread(self, thread_id, name):
        "Set a thread's display name"
        await self.request('thread/name/set', dict(threadId=thread_id, name=name))
        return thread_id

    async def compact_thread(self, thread_id):
        "Start native Codex compaction for a loaded thread"
        return await self.request('thread/compact/start', dict(threadId=thread_id))

    async def close(self):
        if self.proc is not None and self.proc.returncode is None:
            self.proc.terminate()
            await self.proc.wait()

    async def __aenter__(self): return await self.start()
    async def __aexit__(self, *args): await self.close()

# %% ../nbs/04_oai.ipynb #5487a9f1
def tool_turn(prompt, name, arguments, output, answer):
    "A complete synthetic function-call turn"
    call = codex_call(name, arguments)
    return [codex_msg('user',prompt),call,codex_output(call['call_id'],output),codex_msg('assistant',answer)]

def custom_turn(prompt, name, arguments, output, answer):
    "A complete synthetic Codex custom-tool turn"
    call = codex_custom_call(name, arguments)
    return [codex_msg('user',prompt),call,codex_custom_output(call['call_id'],output),codex_msg('assistant',answer)]

# %% ../nbs/04_oai.ipynb #0f4efcb6
def _item_txts(o, skip=()):
    if isinstance(o, str): yield o
    elif isinstance(o, dict): yield from (t for k,v in o.items() if k not in skip for t in _item_txts(v,skip))
    elif is_listy(o): yield from (t for x in o for t in _item_txts(x,skip))

def item_txt(item):
    "Every readable string in a Responses item, joined"
    return '\n'.join(_item_txts(obj2dict(item), skip=('type','id','call_id','encrypted_content','role','status','internal_chat_message_metadata_passthrough')))

def item_role(item):
    "Conversation role of a Responses item"
    item = obj2dict(item)
    if item['type']=='message': return item['role']
    if item['type'] in ('function_call','custom_tool_call'): return 'assistant'
    if item['type'] in ('function_call_output','custom_tool_call_output'): return 'tool'
    return item['type']

def conv_items(items):
    "Conversation-bearing items, excluding reasoning and compaction"
    kinds = {'message','function_call','function_call_output','custom_tool_call','custom_tool_call_output'}
    return L(o for o in items if o.get('type') in kinds)

class ItemHits(list):
    "Search hits with one match-centered preview per line"
    def __repr__(self): return '\n'.join(f"{h.i:5} {h.role:10} {h.preview}" for h in self)

def item_search(
    pat, # Regex to find
    items, # Responses items
    maxlen=160, # Preview characters around the match
):
    "Search model-visible Responses items"
    items,res = conv_items(items),ItemHits()
    for i,o in enumerate(items):
        text = item_txt(o)
        if m := re.search(pat,text):
            h = maxlen//2
            s,e = max(0,m.start()-h),min(len(text),m.end()+h)
            preview = ('…' if s else '')+text[s:e].replace('\n',' ')+('…' if e<len(text) else '')
            res.append(AttrDict(i=i,role=item_role(o),preview=preview,item=o))
    res.items = items
    return res

def show_items(
    items, # Responses items
    mx=500, # Text characters per item
):
    "Readable model history for `items`"
    rows = []
    for o in conv_items(items):
        text = item_txt(o)
        if len(text)>mx: text = text[:mx]+f'…[+{len(text)-mx} chars]'
        rows.append(f"--- {item_role(o)}:{o['type']} ---\n{text}")
    return PrettyString('\n'.join(rows))

# %% ../nbs/04_oai.ipynb #2746cf3e
class PromptHist(list):
    "Codex prompt-history rows, one line per user message"
    def __repr__(self):
        return '\n'.join(f"{h.ts[:16]} {Path(h.project).name:>12} {h.thread[:8]} {h.text.replace(chr(10),' ')[:100]}" for h in self)

def prompt_hist(
    project=None, # Only rollouts whose session cwd is this path
    since=None, # Only record timestamps at or after this ISO string
    pat=None, # Only prompt text matching this regex
    codex_home=CODEX_HOME, # Codex home containing sessions
):
    "User prompts retained in Codex rollouts, oldest first"
    rows = []
    for path in (Path(codex_home)/'sessions').rglob('*.jsonl'):
        recs = load_recs(path)
        meta = first((r.payload for r in recs if r.get('type')=='session_meta'), {})
        tid,cwd = meta.get('id'),meta.get('cwd','')
        if project and cwd!=str(Path(project).expanduser().resolve()): continue
        for r in recs:
            o = r.get('payload',{})
            if r.get('type')!='response_item' or o.get('type')!='message' or o.get('role')!='user': continue
            text = item_txt(o)
            if since and r.get('timestamp','')<since: continue
            if pat and not re.search(pat,text): continue
            rows.append(AttrDict(ts=r.get('timestamp',''),thread=tid,project=cwd,text=text,path=path))
    return PromptHist(sorted(rows,key=lambda x:x.ts))

# %% ../nbs/04_oai.ipynb #b7f0d361
def strip_reasoning(items):
    "Drop Responses API reasoning items"
    return L(items).filter(lambda o:o.get('type')!='reasoning')

def _trunc_deep(o,mx):
    if isinstance(o,str): return o if len(o)<=mx else o[:mx]+f'…[+{len(o)-mx} chars]'
    if isinstance(o,dict): return {k:_trunc_deep(v,mx) for k,v in o.items()}
    if is_listy(o): return [_trunc_deep(x,mx) for x in o]
    return o

def trunc_tools(
    items, # Responses items
    mx=2000, # Maximum characters per string in tool arguments and results
):
    "Copies of `items` with tool arguments and outputs truncated"
    items = [obj2dict(o) for o in items]
    for i,o in enumerate(items):
        if o['type']=='function_call':
            try: args = json.loads(o.get('arguments') or '{}')
            except json.JSONDecodeError: continue
            o['arguments'] = json.dumps(_trunc_deep(args,mx))
        elif o['type']=='custom_tool_call' and (p:=parse_exec(o.get('input',''))):
            o['input'] = exec_input(p.name,_trunc_deep(p.arguments,mx))
        elif o['type'] in ('function_call_output','custom_tool_call_output'): o['output'] = _trunc_deep(o.get('output',''),mx)
    return L(items)

def curate_items(
    recs, # Captured rollout records
    key='', # Salt for deterministic IDs
    mx=None, # Optional tool string cap
):
    "Extract active history, drop reasoning, optionally truncate tools, and re-identify"
    items = strip_reasoning(active_items(recs))
    if mx is not None: items = trunc_tools(items,mx)
    return reid_items(items,key)

# %% ../nbs/04_oai.ipynb #401afdcd
def _customize_items(items):
    items,customs = list(items),set()
    for i,o in enumerate(items):
        if o['type']=='function_call' and o['name'].startswith('tools.'):
            customs.add(o['call_id'])
            items[i] = codex_custom_call(o['name'],json.loads(o['arguments']),o['call_id'])
        elif o['type']=='function_call_output' and o['call_id'] in customs: items[i] = codex_custom_output(o['call_id'],o['output'])
    return L(items)

def dlg2items(
    dlg, # Dialog ending with a prompt
    aim_info=None, # Model capability dict for media handling
):
    "Responses API items for `dlg`, including native custom `exec` calls"
    items = _customize_items(denorm_msgs(dlg2chat(dlg,aim_info)))
    raws,t = {},-1
    for m in dlg.messages:
        if m.msg_type==sprompt: t += 1
        elif m.msg_type==sraw and m.meta.get('item_kind'): raws.setdefault(t,[]).append(dict(m.meta['item']))
    if not raws: return items
    out,t = [],-1
    for o in items:
        if o['type']=='message' and o.get('role')=='user':
            out += raws.get(t,[])
            t += 1
        out.append(o)
    return L([*out,*raws.get(t,[])])

async def dlg2thread(
    dlg, # Dialog to convert
    cwd=None, # Project directory
    codex_home=None, # Codex home
    **kwargs, # Passed to thread/start
):
    "Create a persisted Codex thread whose history is `dlg`"
    async with CodexAppServer(codex_home=codex_home) as app:
        thread = await app.create_thread(reid_items(dlg2items(dlg),dlg.name),cwd=cwd,**kwargs)
    return thread.id

# %% ../nbs/04_oai.ipynb #7b73e471
def _output_text(output):
    if isinstance(output,str): return output
    return '\n'.join(x.get('text','') for x in output if x.get('type') in ('input_text','output_text'))

def _msg_parts(content):
    parts = []
    for c in content:
        if c['type'] in ('input_text','output_text'): parts.append(Part(type=PartType.text,text=c['text']))
        elif c['type']=='input_image': parts.append(Part(type=PartType.input_image,text=c['image_url']))
        else: raise ValueError(f"unsupported message content: {c['type']}")
    return parts

def items2chat(
    items, # Responses API items
):
    "Canonical fastllm messages for editable conversation items"
    msgs,names,customs = [],{},set()
    for o in map(obj2dict,items):
        typ = o['type']
        if typ=='message':
            if o['role'] not in ('user','assistant'): continue
            msgs.append(Msg(role=o['role'],content=_msg_parts(o['content'])))
        elif typ in ('function_call','custom_tool_call'):
            if typ=='custom_tool_call':
                p = parse_exec(o['input'])
                name,args = (p.name,p.arguments) if p else ('exec',dict(input=o['input']))
                customs.add(o['call_id'])
            else: name,args = o['name'],json.loads(o.get('arguments') or '{}')
            names[o['call_id']] = name
            msgs.append(Msg(role='assistant',content=[Part(type=PartType.tool_use,
                data=dict(id=o['call_id'],name=name,arguments=args))]))
        elif typ in ('function_call_output','custom_tool_call_output'):
            cid = o['call_id']
            msgs.append(Msg(role='tool',content=[Part(type=PartType.tool_result,text=_output_text(o.get('output','')),
                data=dict(id=cid,name=names.get(cid),custom=cid in customs))]))
        elif typ in ('reasoning','compaction'): continue
        else: raise ValueError(f'unsupported response item: {typ}')
    return msgs

def chat2dlg(
    msgs, # Canonical messages
    name, # Dialog name
    cls=Dialog, # Dialog class
    mx=2000, # Maximum rendered tool string length; None disables truncation
):
    "A dialog for canonical messages, one prompt per user turn"
    dlg,turns = cls(name),[]
    for m in msgs:
        if m.role=='user': turns.append((m,[]))
        elif turns: turns[-1][1].append(m)
        else: raise ValueError('msgs must start with a user message')
    for u,replies in turns:
        segs,atts = [],[]
        for p in u.content:
            if p.type==PartType.text: segs.append(p.text)
            elif p.type==PartType.input_image:
                mime,data = data_url(p.text)
                atts.append(Attachment(base64.b64decode(data),mime))
                segs.append(f'![](attachment:{atts[-1].id})')
            else: raise ValueError(f'unsupported user part: {p.type}')
        dlg.mk_message('\n\n'.join(segs),msg_type=sprompt,output=hist2fmt(replies,mx=mx),attachments=atts)
    return dlg

def items2dlg(
    items, # Responses API items
    name='thread', # Dialog name
    mx=2000, # Maximum rendered tool string length
):
    "Editable dialog for `items`, preserving developer and compaction items as tagged raws"
    items = L(obj2dict(o) for o in items)
    dlg = chat2dlg(items2chat(items),name,mx=mx)
    prompts = [m for m in dlg.messages if m.msg_type==sprompt]
    raws,t = {},-1
    for o in items:
        if o['type']=='message' and o.get('role')=='user': t += 1
        elif o['type']=='compaction' or (o['type']=='message' and o.get('role') not in ('user','assistant')):
            raws.setdefault(t,[]).append(o)
    for t,group in reversed(list(raws.items())):
        before = prompts[t+1] if t+1<len(prompts) else None
        for o in reversed(group):
            kw = dict(before=before) if before else dict(idx=-1)
            before = dlg.mk_message('',msg_type=sraw,meta=dict(item_kind=o['type'],item=o),**kw)
    return dlg

def thread2dlg(
    thread_id=None, # Thread UUID; current thread if None
    codex_home=CODEX_HOME, # Codex home
    name=None, # Dialog name
    mx=2000, # Maximum rendered tool string length
    recs=None, # Already-loaded rollout records
):
    "The active model history of a Codex thread as a dialog"
    thread_id = thread_id or cur_thread()
    recs = load_rollout(thread_id,codex_home) if recs is None else recs
    return items2dlg(active_items(recs),name or thread_id or 'thread',mx)

# %% ../nbs/04_oai.ipynb #5a2dce10
def resolve_thread(
    ref=None, # Thread UUID; current thread if None
    codex_home=CODEX_HOME, # Codex home
):
    "Resolve a thread UUID to `(thread_id, rollout_path)`"
    ref = ref or cur_thread()
    path = rollout_file(ref,codex_home)
    if not path: raise FileNotFoundError(f'No Codex thread {ref!r}')
    return ref,path
